name: Уведомление
description: 'Уведомления помогают информировать сообщество о важной информации, которую бюро или офис хотят выделить в течение ограниченного периода времени. Они могут быть отклонены членом сообщества.'
help: null
