third_party_settings:
  toc_js:
    title: Оглавление
    back_to_top_label: 'Вернуться к вершине'
name: Ресурс
description: 'Ресурс — это контент или приложение, не размещенное на Portland.gov или не подлежащее индексированию на Portland.gov, например, представление поиска. Ресурсы могут использоваться для служб штата, округа и городских агломераций для создания результатов поиска со сводкой. Ресурсы также можно использовать для создания ссылки, которая может указывать на поиск. (например, «Найти парк» — это ресурс, потому что страница в /parks/search недоступна для нашего поискового индекса или недоступна для показа.)'
help: null
