display:
  default:
    display_title: Основной
    display_options:
      exposed_form:
        options:
          submit_button: Применить
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      pager:
        options:
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
          tags:
            previous: '‹ Предыдущий'
            next: 'Следующий ›'
            first: '« Первая'
            last: 'Последняя »'
      fields:
        status:
          label: Статус
          format_plural_string: !!binary QGNvdW50A0Bjb3VudANAY291bnRbMl0=
        label:
          label: Метка
        item_type:
          label: Тип
        word_count:
          label: Слова
        operations:
          label: Операции
      arguments:
        tltid:
          exception:
            title: Все
  block_1:
    display_title: Блок
