label: 'Locked content'
display:
  default:
    display_title: Основной
    display_options:
      exposed_form:
        options:
          submit_button: Применить
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
            first: '« Первая'
            last: 'Последняя »'
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
      fields:
        title:
          label: Заголовок
          separator: ', '
        type:
          label: 'Тип материала'
          separator: ', '
        timestamp:
          label: 'Locked since'
        name:
          separator: ', '
        operations:
          label: Операции
      filters:
        status:
          expose:
            label: 'Статус публикации'
          group_info:
            label: 'Статус публикации'
            group_items:
              1:
                title: Опубликовано
              2:
                title: 'Снято с публикации'
        type:
          expose:
            label: 'Тип материала'
        title:
          expose:
            label: Заголовок
      title: 'Locked content'
  page_1:
    display_title: Страница
    display_options:
      menu:
        title: 'Locked content'
