title: 'Сообщить о граффити'
description: 'Сообщите о граффити на общественной собственности или запросите помощь в удалении на частной собственности.'
category: Отчет
elements: |
  section_report:
    '#title': Отчет
  report_location:
    '#title': Расположение
    '#default_value':
      location_type: улица
      location_park: null
      location_address: null
      place_name: null
      location_details: null
      location_lat: null
      location_lon: null
      location_private_owner: null
    '#location_map__description': "<em>Существующие отчеты о граффити отображаются с красным маркером <img src=\"/modules/custom/portland/modules/portland_location_picker/images/map_marker_incident.png\" alt=\"Красный значок маркера карты\" class=\"inline-icon\"> когда карта полностью увеличена. Новые отчеты должны быть просмотрены, и может пройти до 2\_рабочих дней, прежде чем они появятся на карте.</em>"
    '#location_type__title': 'На каком объекте находится проблема?'
    '#location_park_container__title': 'Контейнер списка парков'
    '#waterway_instructions__title': 'Инструкции по водным путям'
    '#location_private_owner__title': 'Вы владелец недвижимости?'
    '#location_address__title': 'Адрес или перекресток'
    '#location_map__title': 'Карта местности'
    '#suggestions_modal__title': Предложения
    '#status_modal__title': 'Индикатор состояния'
    '#place_name__title': 'Укажите имя'
    '#location_details__title': 'Детали местоположения'
    '#location_lat__title': Широта
    '#location_lon__title': Долгота
    '#location_asset_id__title': 'Идентификатор объекта'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  markup_select_to_continue:
    '#markup': 'Сделайте выбор, чтобы продолжить.'
  report_hate_speech_or_gang:
    '#title': 'Это граффити разжигает ненависть или связано с бандой?'
    '#options':
      'Yes': Да
      'No': Нет
      'Not sure': 'Не уверена'
  report_property_owner_assistance:
    '#title': 'Что бы вы хотели попросить?'
    '#options':
      Assistance: 'Запросите бесплатную или недорогую помощь по удалению граффити в программе граффити Civic Life.'
      'Removal Kit': 'Запросите набор для удаления граффити или узнайте больше об инициативе «Очисти, закрась».'
  report_private_property_type:
    '#title': 'Какой это тип собственности?'
  report_corporate_franchise:
    '#title': 'Вы корпоративная франшиза?'
  report_business_employees_amt:
    '#title': 'Сколько сотрудников в бизнесе?'
  report_building_units_amt:
    '#title': 'Сколько квартир в здании/комплексе?'
  report_nonprofit_employees:
    '#title': 'Сколько сотрудников в некоммерческой организации?'
  report_contractor_text:
    '#admin_title': 'Не подходит'
    '#markup': '<div class="alert alert--info next-steps"><h2>Вы не имеете права на помощь по удалению граффити [должно ли это быть тупиком, или мы все еще хотим, чтобы пользователь отправил форму?]</h2><p> Информация о подрядчике здесь...</p></div>'
  report_removal_kit_text:
    '#markup': '<div class="alert alert--info next-steps"><h2>Следующие шаги [мы хотим, чтобы это было тупиком или чтобы пользователь отправил форму?]</h2><p> Вот как запросить комплект........</p></div>'
  markup_qualifies:
    '#markup': '<div class="alert alert--info next-steps"><h2>Вы можете претендовать на помощь в удалении граффити</h2><p> Пожалуйста, продолжайте заполнять этот отчет.</p></div>'
  report_tenant_or_neighbor:
    '#title': 'Вы сосед или арендатор квартиры?'
    '#options':
      'I am a tenant': 'я арендатор'
      'I am a neighbor or community member': 'Я сосед или член сообщества'
  report_tenant_text:
    '#markup': '<div class="alert alert--info next-steps"><h2>Следующие шаги</h2><p> Пожалуйста, поговорите с владельцем собственности.</p></div>'
  report_above_ground_level:
    '#title': 'Находится ли граффити над уровнем земли (более 8 футов)?'
    '#options':
      'Yes': Да
      'No': Нет
      'Not sure': 'Не уверена'
  report_graffiti_on_mural:
    '#title': 'Граффити на фреске?'
  report_repeat_offender:
    '#title': 'Вы видели это граффити или тег раньше? Это от рецидивиста?'
  report_photo:
    '#title': 'Пожалуйста, загрузите фото граффити'
    '#description': 'Четкое фото граффити помогает нам определить, на какой поверхности оно расположено и какие ресурсы могут потребоваться для его устранения.'
  section_contact:
    '#title': 'Ваши Контактные Данные'
  contact_name:
    '#title': Имя
  contact_email:
    '#title': 'Эл. адрес'
    '#description': 'Мы будем использовать вашу электронную почту, чтобы ответить на ваш отзыв или запрос. Он не будет публиковаться в публичных отчетах, но будет доведен до сведения городских служащих.'
  section_public_records_statement:
    '#title': 'Заявление о публичных записях'
  public_records_statement_standard:
    '#markup': 'Информация, которую вы предоставляете городским властям, является общедоступной и может подлежать обнародованию в соответствии с <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">Законом штата Орегон о государственных записях</a> . Этот закон классифицирует определенную информацию как доступную для общественности по запросу. См. наше <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">заявление о конфиденциальности</a> для получения дополнительной информации.'
  section_agent_use_only:
    '#title': 'Только использование агента'
  agent_email:
    '#title': 'Электронная почта агента'
    '#default_value': '[текущий-пользователь:отображаемое-имя] <[текущий-пользователь:почта]>'
  agent_ticket_number:
    '#title': 'Номер билета'
  agent_action_taken:
    '#title': 'Действие предпринято'
    '#options':
      Resolved: Решено
      Referred: Направлено
  admin_contact_type:
    '#title': 'Тип контакта'
    '#options':
      Phone: Телефон
      'Requested Callback': 'Запрошенный обратный вызов'
      Email: 'Эл. адрес'
      Webform: Веб-форма
      'In Person': Лично
      Webchat: Веб-чат
      'Social Media': 'Социальные медиа'
  agent_ticket_type:
    '#title': 'Тип билета'
    '#options':
      Question: Вопрос
      Incident: Инцидент
      Problem: Проблема
      Task: Задача
  agent_summary:
    '#title': 'Резюме агента'
  computed_priority:
    '#title': приоритет
  actions:
    '#title': 'Кнопка(и) Отправить'
  report_ticket_id:
    '#title': 'Идентификатор обращения в службу поддержки'
  ticket_description:
    '#title': 'Описание билета'
  resolution_url:
    '#title': 'URL разрешения'
  waiver_url:
    '#title': 'URL-адрес отказа'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: 'Отправить другой отчет'
  limit_total_message: null
  limit_user_message: null
handlers:
  create_new_zendesk_ticket:
    label: 'Создать новый тикет Zendesk'
    notes: null
