title: 'Сообщить о дискриминации'
description: null
category: Отчет
elements: |
  confidentiality_waiver:
    '#title': 'Отказ от конфиденциальности'
    '#description': 'Политикой города является сохранение конфиденциальности информации, которую вы предоставляете в этой форме, в целях выполнения вашего запроса. Городские власти также попытаются сохранить конфиденциальность вашей информации в случае, если кто-то потребует, чтобы она была опубликована в качестве общедоступного документа в соответствии с <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">Законом штата Орегон о государственных документах</a> . Если вы предпочитаете отказаться от этой конфиденциальности, выберите этот вариант ниже.'
    '#options':
      'I do not waive confidentiality.': 'Я <em>не</em> отказываюсь от конфиденциальности.'
      'I choose to waive confidentiality.': 'Я отказываюсь от конфиденциальности.'
  report_discrimination:
    '#title': 'Хотели бы вы подать жалобу на политику города или действия, предпринятые городской программой, сотрудником или подрядчиком, которые нарушают ваши права и дискриминируют вас?'
    '#options':
      'Yes': 'Да, я хотел бы сообщить о дискриминации'
      'No': 'Нет, но я хотел бы запросить размещение ADA'
  request_ada_accommodation_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Следующие шаги</h2><p> Пожалуйста, сделайте запрос через городскую службу <a href="/311/ada-request">размещения ADA</a> . Вы также можете позвонить нам по телефону <a href="tel:+1-503-823-4000">503-823-4000</a> или телетайпу через службу ретрансляции штата Орегон: <a href="tel:711">711</a> . Персонал готов помочь с понедельника по пятницу с 8:00 до 17:00.</p></div>'
  report_how_to_complete:
    '#title': 'Как бы вы хотели завершить свой запрос или отчет?'
    '#options':
      'Call us': 'Позвоните нам'
      'We contact you': 'Мы можем связаться с вами'
      'Continue online': 'Продолжить онлайн'
  markup_contact_us_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Следующие шаги</h2><p> Позвоните нам по номеру 311, <a href="tel:+15038234000">(503) 823-4000</a> или <a href="tel:711">711</a> для телетайпа через службу ретрансляции штата Орегон. Персонал доступен с понедельника по пятницу с 8:00 до 17:00, кроме государственных праздников.</p></div>'
  report_discrimination_basis:
    '#title': 'Я считаю, что дискриминация, с которой я столкнулась, была основана на...'
    '#description': '(Проверить все, что относится)'
  report_discrimination_date:
    '#title': 'Когда произошла дискриминация?'
  report_discrimination_location:
    '#title': 'Где произошла дискриминация?'
    '#location_type__title': 'На каком объекте находится проблема?'
    '#location_park_container__title': 'Контейнер списка парков'
    '#waterway_instructions__title': 'Инструкции по водным путям'
    '#location_private_owner__title': 'Вы владелец недвижимости?'
    '#location_address__title': 'Адрес или перекресток'
    '#location_map__title': 'Карта местности'
    '#suggestions_modal__title': Предложения
    '#status_modal__title': 'Индикатор состояния'
    '#place_name__title': 'Укажите имя'
    '#location_details__title': 'Детали местоположения'
    '#location_lat__title': Широта
    '#location_lon__title': Долгота
    '#location_asset_id__title': 'Идентификатор объекта'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  report_discrimination_bureau_office_etc:
    '#title': 'Укажите название городского бюро, офиса, сотрудника, мероприятия или программы, связанной с дискриминацией.'
  report_discrimination_description:
    '#title': 'Своими словами опишите предполагаемую дискриминацию.'
    '#description': 'Пожалуйста, объясните, что произошло; кто был вовлечен; какая политика, программа или деятельность были дискриминационными (если применимо); почему вы считаете, что это произошло, и как вы подверглись дискриминации. Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.'
  report_discrimination_witnesses:
    '#title': 'Были ли свидетели дискриминации?'
  report_discrimination_witnesses_contact_known:
    '#title': 'Знаете ли вы их имя и номер телефона или адрес электронной почты?'
    '#description': 'Со свидетелями будут связываться только в случае необходимости для расследования вашего заявления. В случае контакта свидетели могут выбрать, хотят ли они участвовать в процессе расследования.'
  report_discrimination_witness_1_name:
    '#title': 'Имя первого свидетеля'
  report_discrimination_witness_1_phone:
    '#title': 'Телефон первого свидетеля'
  report_discrimination_witness_1_email:
    '#title': 'Электронная почта первого свидетеля'
  report_discrimination_add_witness:
    '#title': 'Добавить еще одного свидетеля?'
    '#options':
      'Add another witness': 'Добавить еще одного свидетеля'
  report_discrimination_witness_2_name:
    '#title': 'Имя второго свидетеля'
  report_discrimination_witness_2_phone:
    '#title': 'Телефон второго свидетеля'
  report_discrimination_witness_2_email:
    '#title': 'Электронная почта второго свидетеля'
  report_discrimination_file_upload:
    '#title': 'При необходимости приложите к жалобе любые фотографии или другие материалы.'
  report_discrimination_desired_outcome:
    '#title': 'Какое действие или решение вы хотели бы видеть принятым?'
  report_discrimination_filed_complaint_other:
    '#title': 'Подавали ли вы жалобу в какие-либо другие федеральные органы, органы штата или местные органы или в какой-либо федеральный суд или суд штата?'
    '#description': 'Вы имеете право обратиться в любое агентство или суд. Подача жалобы в другое учреждение или суд не мешает вам подать жалобу в город Портленд. В определенных ситуациях агентства будут координировать свои действия, чтобы обеспечить расследование жалобы соответствующим агентством или судом.'
    '#options':
      'Yes': Да
      'No': Нет
      'Prefer not to answer': 'предпочитаю не отвечать'
  report_discrimination_filed_complaint_other_agency:
    '#title': 'Какой орган или суд?'
  report_discrimination_filed_complaint_other_agency_contact_name:
    '#title': 'Агентство или контактное лицо в суде'
  report_discrimination_filed_complaint_other_agency_contact_phone:
    '#title': 'Контактный телефон агентства или суда'
  report_discrimination_on_behalf_of:
    '#title': 'К кому вы обращаетесь с этой просьбой или жалобой?'
    '#options':
      Myself: Сам
      'Someone else': 'Кто-нибудь другой'
  report_discrimination_on_behalf_of_name:
    '#title': 'Как их зовут?'
  report_discrimination_on_behalf_of_relationship:
    '#title': 'Каково ваше отношение к ним?'
  report_discrimination_on_behalf_of_permission:
    '#title': 'Вы получили от них разрешение на подачу этой жалобы? Или у вас есть правовые отношения, которые позволяют вам подать жалобу от их имени?'
  report_discrimination_on_behalf_of_permission_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Следующие шаги</h2><p> Пожалуйста, получите их разрешение перед отправкой этой формы.</p></div>'
  contact_name:
    '#title': 'Ваше имя'
  contact_email:
    '#title': 'Эл. адрес'
    '#description': 'Мы будем использовать вашу электронную почту, чтобы подтвердить вашу заявку.'
  contact_phone:
    '#title': Телефон
  contact_preferred_method:
    '#title': 'В случае необходимости вы бы предпочли, чтобы мы связались с вами по телефону или электронной почте?'
    '#options':
      Phone: Телефон
      Email: 'Эл. адрес'
  contact_interpreter:
    '#title': 'Вам нужен переводчик?'
    '#options':
      'No': Нет
      'Yes, VRI (Video Remote Interpretation)': 'Да, VRI (удаленный перевод видео)'
      'Yes, Oregon Relay Service': 'Да, служба ретрансляции штата Орегон'
      'Yes, language interpreter': 'Да, языковой переводчик'
  contact_language:
    '#title': 'На каком языке?'
  markup_complainant_acknowledgement_text:
    '#markup': '<p><strong>Заявитель Подтверждение</strong></p><p> Отправляя эту форму, я подтверждаю, что (1) я прочитал, понял и принимаю <a href="/code/23">условия процедур отслеживания и расследования жалоб на гражданские права</a> и (2) информация, которую я предоставил в этой форме, является достоверной, насколько мне известно.</p>'
  complainant_acknowledgement_agree:
    '#title': 'Я согласен'
  section_agent_use_only:
    '#title': 'Только использование агента'
  agent_email:
    '#title': 'Электронная почта агента'
    '#default_value': '[текущий-пользователь:отображаемое-имя] <[текущий-пользователь:почта]>'
  agent_ticket_number:
    '#title': 'Номер билета'
  agent_action_taken:
    '#title': 'Действие предпринято'
  agent_contact_type:
    '#title': 'Тип контакта'
  agent_ticket_type:
    '#title': 'Тип билета'
  agent_summary:
    '#title': 'Резюме агента'
  report_ticket_id:
    '#title': 'Сообщить об идентификаторе заявки'
  actions:
    '#title': 'Кнопки отправки'
    '#submit__label': 'Представлять на рассмотрение'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_new_ticket:
    label: 'Zendesk новый тикет'
    notes: 'Создает новую заявку на жалобу на дискриминацию и назначает ее группе 311: ADA и дискриминации.'
