title: 'Связаться с избранным должностным лицом'
description: 'Используется для отправки отзывов непосредственно избранным должностным лицам и для запроса встреч.'
category: null
elements: |
  introductory_text:
    '#markup': '<p>Предоставьте отзыв о политике или действиях города Портленд или запросите встречу с мэром, уполномоченным города или городским аудитором.</p>'
  purpose:
    '#title': 'Чем бы Вы хотели заняться?'
    '#options':
      provide_feedback_council: 'Предоставление комментариев или отзывов по теме членам городского совета'
      provide_feedback: 'Предоставьте комментарий или отзыв по теме всем городским избранным должностным лицам'
      provide_feedback_specific_elected: 'Предоставление комментариев или отзывов конкретным выборным должностным лицам'
      request_meeting: 'Запросить встречу с избранным должностным лицом или попросить его выступить на мероприятии'
      provide_testimony: 'Дайте показания по предстоящему пункту повестки дня'
  section_provide_testimony:
    '#title': 'Дайте показания по предстоящему пункту повестки дня'
  testimony_instructions:
    '#markup': 'Письменные показания могут быть представлены по отдельным вопросам повестки дня. Свидетельские показания будут переданы городскому совету и персоналу. Он будет включен в публичный отчет в соответствии с <a href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon%27s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">Законом штата Орегон об публичных записях</a> .<br /><br /> Отправьте письменные показания по электронной почте <a href="mailto:cctestimony@portlandoregon.gov">cctestimony@portlandoregon.gov</a> .<br /><br /> <a href="/council/agenda">Просмотр предстоящих повесток дня</a>'
  section_provide_feedback:
    '#title': 'Предоставьте комментарий или отзыв по теме всем городским избранным должностным лицам'
  elected_officials_feedback_title:
    '#markup': '<h2>Предоставьте комментарий или отзыв по теме всем городским избранным должностным лицам</h2>'
  markup:
    '#markup': '<h2>Предоставление комментариев или отзывов по теме членам городского совета</h2>'
  feedback_topics_entity:
    '#title': 'Выберите одну или несколько подходящих тем'
  feedback_topic_other:
    '#title': 'Другая тема, не указанная выше'
  feedback_recipients_entity_all:
    '#title': 'Кому мы должны отправить ваш комментарий или отзыв'
    '#options_all_text': 'я не уверен'
  section_request_meeting:
    '#title': 'Запросить встречу с избранным должностным лицом или попросить его выступить на мероприятии'
  meeting_recipients_entity:
    '#title': 'Кому мы должны отправить ваш запрос?'
  meeting_event_type:
    '#title': 'На что бы вы хотели их пригласить?'
    '#options':
      'Attend an event': 'Посетить мероприятие'
      'Speak at an event': 'Выступить на мероприятии'
      'Speak at a meeting': 'Выступить на собрании'
      'Meet with me or my group': 'Встреча со мной или моей группой'
  meeting_title:
    '#title': 'Название мероприятия или встречи'
  meeting_description:
    '#title': 'Описание события/встречи'
    '#description': '<p data-renderer-start-pos="2355">Пожалуйста, предоставьте краткое описание мероприятия/встречи, его местонахождение, цель, аудиторию, количество людей, которые будут присутствовать, и любую другую важную информацию.</p>'
  meeting_preferred_datetime:
    '#title': 'Желаемая дата и время встречи'
  meeting_alternate_datetime:
    '#title': 'Альтернативная дата и время встречи'
  meeting_duration:
    '#title': 'Сколько времени вы запрашиваете?'
    '#options':
      '15 minutes or less': '15 минут или меньше'
      '30 minutes': '30 минут'
      '1 hour': '1 час'
      'More than 1 hour': 'более 1 часа'
  meeting_phone:
    '#title': 'Номер телефона'
    '#description': 'Пожалуйста, укажите свой номер телефона, чтобы мы могли связаться с вами и запланировать ваш запрос, если он будет одобрен.'
  section_feedback_specific_official:
    '#title': 'Предоставление комментариев или отзывов конкретным выборным должностным лицам'
  feedback_recipients_entity:
    '#title': 'Кому мы должны отправить ваш комментарий или отзыв (выберите все подходящие варианты)'
    '#options_all_text': 'я не уверен'
  feedback_specific_not_sure:
    '#title': 'Не уверен'
  feedback_specific_official_link:
    '#markup': '<a href="/elected-officials">Просмотр текущих заданий бюро по должностным лицам</a>'
  feedback_comments:
    '#title': 'Что бы вы хотели сказать?'
    '#description': '<p data-pm-slice="1 1 []">Четкие краткие комментарии и отзывы приветствуются.</p>'
  section_contact_information:
    '#title': 'Ваши Контактные Данные'
  contact_name:
    '#title': Имя
  contact_email_address:
    '#title': 'Адрес электронной почты'
  contact_country:
    '#title': Страна
  contact_street_address:
    '#title': 'Адрес улицы'
  contact_unit_type:
    '#title': 'Тип устройства'
  contact_unit_number:
    '#title': 'Номер блока'
  contact_city:
    '#title': Город
  contact_state:
    '#title': Состояние
  contact_postal_code:
    '#title': 'Почтовый индекс'
  contact_international_address:
    '#title': 'Международный почтовый адрес'
  section_public_records_statement:
    '#title': 'Заявление о публичных записях'
  public_records_statement_text:
    '#markup': 'Информация, которую вы предоставляете городским властям, является общедоступной и может подлежать обнародованию в соответствии с <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">Законом штата Орегон о государственных записях</a> . Этот закон классифицирует определенную информацию как доступную для общественности по запросу. См. наше <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">заявление о конфиденциальности</a> для получения дополнительной информации.'
  voting_electeds_entity:
    '#title': 'Голосование избранных'
  computed_recipient_list:
    '#title': 'Список получателей'
  computed_subject:
    '#title': Предмет
  computed_confirmation_message:
    '#title': 'Вычисляемое подтверждающее сообщение'
  actions:
    '#title': 'Кнопки отправки'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: 'Спасибо за ваш вклад'
  confirmation_message: '[webform_submission:values:computed_confirmation_message:htmldecode]<br />'
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  email_2:
    label: 'Отправить электронное письмо выбранным избранным'
    notes: null
    settings:
      from_name: null
      reply_to: null
      return_path: null
      sender_name: null
      subject: null
      body: null
