title: 'Запрос на размещение ADA'
description: null
elements: |
  section_public_records_statement:
    '#title': 'Заявление о публичных записях'
  public_records_statement_standard:
    '#markup': '<strong>Заявление о публичных записях</strong><br /> Информация, которую вы предоставляете городским властям, является общедоступной и может подлежать обнародованию в соответствии с <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">Законом штата Орегон о государственных записях</a> . Этот закон классифицирует определенную информацию как доступную для общественности по запросу. См. наше <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">заявление о конфиденциальности</a> для получения дополнительной информации.'
  request_how:
    '#title': 'Как бы вы хотели сделать свой запрос?'
    '#options':
      'I will contact the City': 'Я свяжусь с городом'
      'I would like the City to contact me': 'Я хочу, чтобы администрация города связалась со мной'
      'I will continue with the online form': 'Я продолжу онлайн-форму'
  request_call_city_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Следующие шаги</h2><p> Позвоните нам по телефону <a href="tel:311">311</a> , <a href="tel:+15038234000">(503) 823-4000</a> или <a href="tel:711">711</a> для телетайпа через службу ретрансляции штата Орегон. Персонал доступен с понедельника по пятницу с 8:00 до 17:00, кроме государственных праздников.</p></div>'
  request_how_continue_text:
    '#markup': 'Сделайте выбор, чтобы продолжить.'
  container_confidentiality:
    '#title': Конфиденциальность
  confidentiality_waiver:
    '#title': 'Отказ от конфиденциальности'
    '#description': 'Политикой города является сохранение конфиденциальности информации, которую вы предоставляете в этой форме. Ваша информация будет храниться в тайне, если вы не установите флажок, подтверждающий, что вы хотите отказаться от конфиденциальности.'
    '#options':
      'I do not waive confidentiality': 'Я <em>не</em> отказываюсь от конфиденциальности.'
      'I waive confidentiality': 'Я отказываюсь от конфиденциальности.'
  request_what:
    '#title': 'Я хотел бы попросить, чтобы город...'
    '#options':
      event_accommodations: 'Предоставление жилья для городского мероприятия, мероприятия или программы'
      city_materials: 'Предоставлять городские материалы в доступном для меня формате'
      remove_barrier: 'Убрать барьер или облегчить мне доступ к улице, тротуару, тропе, парку или другому пространству, принадлежащему городу (например, убрать препятствие на тротуаре, добавить пешеходные переходы или улучшить указатели)'
      change_policy: 'Измените или модифицируйте политику или процедуру (например, разрешите членам сообщества с ограниченными возможностями досрочно посещать мероприятие, разрешите сопровождающему лицу посещать занятия или мероприятия)'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': null
    '#other__description': 'Пожалуйста, опишите ваш запрос. Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.'
  container_materials:
    '#title': 'Запросить материалы'
  request_materials_type:
    '#title': 'Материалы, которые вы запрашиваете...'
    '#options':
      website: 'на сайте города?'
      event: 'для конкретного события или мероприятия?'
      printed: 'печатный документ недоступен в Интернете?'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': null
    '#other__description': 'Пожалуйста, опишите материалы.'
  request_materials_url:
    '#title': 'Каков веб-адрес (URL) страницы, на которой размещены материалы?'
  request_materials_description:
    '#title': 'Название и/или описание документа'
  container_event:
    '#title': 'Детали события'
  request_event_name:
    '#title': 'Название мероприятия, события или программы'
  request_event_date:
    '#title': 'Дата события'
  request_event_location:
    '#title': 'Место проведения'
  request_event_bureau_sponsor:
    '#title': 'Организатор мероприятия'
    '#description': 'Пожалуйста, укажите городское бюро, офис, программу, проект или выборное должностное лицо, которое проводит мероприятие, если вы знаете.'
  request_event_url:
    '#title': 'URL-адрес сведений о событии'
    '#description': 'Скопируйте и вставьте URL-адрес веб-сайта мероприятия, программы или материала, если он известен.'
  container_event_accommodations:
    '#title': 'Размещение на мероприятиях'
  request_event_accommodations_type:
    '#title': 'Какой тип размещения вы запрашиваете?'
    '#description': 'Проверить все, что относится.'
    '#options':
      accessible_parking: 'Доступная парковка'
      accessible_entrance: 'Доступный вход на мероприятие и маршруты к туалетам'
      communication_aids: 'Коммуникационные средства'
      accessible_materials: 'Материалы в доступном формате'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': null
    '#other__description': 'Пожалуйста, опишите ваш запрос. Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.'
  request_event_communiation_aids_type:
    '#title': 'Какой тип средств связи вы бы предпочли?'
    '#options':
      captioning: Субтитры
      listening_device: 'Вспомогательное прослушивающее устройство'
      interpretation_asl: 'Интерпретация в ASL'
      interpretation_other: 'Интерпретация на другом жестовом или тактильном языке'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': null
    '#other__description': 'Пожалуйста, опишите ваш запрос. Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.'
  request_event_materials_format:
    '#title': 'Какой формат материалов мероприятия вы бы предпочли?'
    '#options':
      accessble_word_doc: 'Доступный электронный документ (Microsoft Word)'
      accessible_pdf: 'Доступный электронный документ (PDF)'
      large_print: 'Бумага с крупным шрифтом'
      braille: 'шрифт Брайля'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': null
    '#other__description': 'Пожалуйста, опишите ваш запрос. Чтобы защитить вашу конфиденциальность, не включайте никакую личную информацию или информацию, связанную со здоровьем.'
  container_remove_barrier:
    '#title': 'Удалить барьер'
  request_barrier_type:
    '#title': 'О какой проблеме вы сообщаете? Как мы можем облегчить вам доступ?'
    '#options':
      barrier: 'Барьер - есть барьер, препятствие или что-то на пути, препятствующее доступу.'
      parking: 'Парковка - Нет доступной парковки или есть проблема с существующими местами'
      signage: 'Вывески - Знаки отсутствуют или знаки нечеткие'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': null
    '#other__description': 'Пожалуйста, опишите.'
  report_location:
    '#title': 'Расположение барьера или проблемы'
    '#default_value':
      location_type: null
      location_park: null
      location_address: null
      place_name: null
      location_details: null
      location_lat: null
      location_lon: null
      location_private_owner: null
    '#location_type__title': 'На каком объекте находится проблема?'
    '#location_park_container__title': 'Контейнер списка парков'
    '#waterway_instructions__title': 'Инструкции по водным путям'
    '#location_private_owner__title': 'Вы владелец недвижимости?'
    '#location_address__title': 'Адрес или перекресток'
    '#location_map__title': 'Карта местности'
    '#suggestions_modal__title': Предложения
    '#status_modal__title': 'Индикатор состояния'
    '#place_name__title': 'Укажите имя'
    '#location_details__title': 'Детали местоположения'
    '#location_lat__title': Широта
    '#location_lon__title': Долгота
    '#location_asset_id__title': 'Идентификатор объекта'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  report_barrier_description:
    '#title': 'Описание проблемы'
    '#description': 'Пожалуйста, подробно опишите проблему. Как мы можем упростить доступ к вашему городу? Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.'
  container_change_policy:
    '#title': 'Изменить политику'
  report_policy_request:
    '#title': 'Какова ваша просьба?'
    '#description': 'Пожалуйста, опишите изменение политики или процедуры, которое вы запрашиваете. Чтобы защитить вашу конфиденциальность, не указывайте никакую личную информацию или информацию, связанную со здоровьем.'
  section_contact:
    '#title': Контакты
  contact_name:
    '#title': 'Ваше имя'
  contact_email:
    '#title': 'Ваш адрес электронной почты'
    '#description': 'Мы будем использовать вашу электронную почту, чтобы ответить на ваш отзыв или запрос.'
  contact_phone:
    '#title': Телефон
  contact_prefer_phone:
    '#title': 'Вы бы предпочли, чтобы мы связались с вами по телефону или электронной почте?'
    '#options':
      Phone: Телефон
      Email: 'Эл. адрес'
  contact_phone_assistance_type:
    '#title': 'Если вам нужна помощь по телефону, выберите один из вариантов'
    '#options':
      vri: ВРИ
      relay: 'Служба ретрансляции штата Орегон (TTY)'
      interpreter: 'Устный переводчик'
      none: 'Ни один из вышеперечисленных'
  contact_request_on_behalf_of:
    '#title': 'К кому вы обращаетесь с этой просьбой или жалобой?'
    '#options':
      myself: Сам
      other: 'Кто-нибудь другой'
  contact_behalf_name:
    '#title': 'Как их зовут?'
  section_agent_use_only:
    '#title': 'Только использование агента'
  agent_email:
    '#title': 'Электронная почта агента'
    '#default_value': '[текущий-пользователь:отображаемое-имя] <[текущий-пользователь:почта]>'
  agent_ticket_number:
    '#title': 'Номер билета'
  agent_action_taken:
    '#title': 'Действие предпринято'
  agent_contact_type:
    '#title': 'Тип контакта'
  agent_ticket_type:
    '#title': 'Тип билета'
  agent_summary:
    '#title': 'Резюме агента'
  report_ticket_id:
    '#title': 'Сообщить об идентификаторе заявки'
  computed_location_address:
    '#title': 'Расчетный адрес местоположения'
  computed_location_latlon:
    '#title': 'Вычисленное местоположение Латлон'
  actions:
    '#title': 'Кнопки отправки'
    '#submit__label': 'Представлять на рассмотрение'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: 'Спасибо за отправку вашего запроса!'
  confirmation_message: 'Ваш запрос получен, с вами свяжутся в течение 48 часов.'
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_new_ticket:
    label: 'Zendesk новый тикет'
    notes: 'Создает новый билет запроса на размещение ADA и назначает его группе 311.'
