title: 'Сообщить об электронном скутере - Решение'
description: 'Используется агентами компании-производителя скутеров для сообщения о решении проблем, представленных членами сообщества. Ссылка на эту форму, включая значения строки запроса для предварительного заполнения полей, отправляется компании-производителю скутеров для каждого отчета.'
elements: |
  report_issue:
    '#title': 'В чем проблема с электронным самокатом?'
    '#options':
      'improperly parked': 'Электросамокат неправильно припаркован'
      damaged: 'Электросамокат поврежден или работает неправильно'
      'riding on sidewalk': 'Пользователь едет по тротуару'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': 'Пожалуйста, опишите...'
  report_blocking:
    '#title': 'Блокирует ли электросамокат тротуар, тропу, велосипедную дорожку, подъездную дорожку, улицу, остановку общественного транспорта или другую транспортную полосу?'
  report_private_property:
    '#title': 'Электросамокат припаркован на частной территории?'
  issue_resolution:
    '#title': 'Решение проблемы'
    '#options':
      'Scooter has been moved': 'Скутер был перемещен'
      'Scooter has been taken in for repairs': 'Скутер забрали на ремонт.'
      'Scooter has been fixed on location': 'Скутер был зафиксирован на месте'
      'Upon inspection, scooter does not appear to be out of compliance': 'При осмотре скутер не выглядит несоответствующим'
      'Incorrect e-scooter company selected by community member': 'Участник сообщества выбрал неверную компанию по производству электронных скутеров. Пожалуйста, выберите правильную компанию ниже. Билет будет перенаправлен.'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': 'Пожалуйста, опишите...'
  report_company:
    '#title': 'Компания по производству электросамокатов (e-scooter)'
    '#description': 'Какой компании по производству электронных скутеров принадлежит скутер? Или какого цвета электронный скутер?'
    '#options':
      Bird: 'Птица (черный)'
      Bolt: 'Болт (черный и желтый)'
      Lime: 'Лайм (зеленый)'
      Spin: 'Спин (оранжевый)'
      'Not sure': 'Не уверена'
  report_asset_id:
    '#title': 'Идентификатор электронного скутера'
  report_ticket_id:
    '#title': 'Идентификатор обращения в службу поддержки'
    '#description': 'Если вы нажмете ссылку разрешения в отправленном нами электронном уведомлении, это значение будет введено автоматически.'
  company_rep_id:
    '#title': 'Представитель компании'
    '#description': 'Пожалуйста, введите свое имя, инициалы или другой уникальный идентификатор на случай, если возникнут вопросы по поводу разрешения этого отчета.'
  original_submission_key:
    '#title': 'Исходный ключ отправки'
  actions:
    '#title': 'Кнопки отправки'
    '#submit__label': 'Представлять на рассмотрение'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: 'Билет обновлен'
  confirmation_message: 'Благодарим вас за отправку отчета о разрешении. Ваш ответ записан, тикет обновлен.'
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  resolve_ticket:
    label: 'Решить тикет'
    notes: null
  reroute_ticket:
    label: 'Перенаправить билет'
    notes: 'Перенаправляет заявку в другую компанию, если неправильная компания была выбрана участником сообщества.'
  zendesk_ticket_validator:
    label: 'Валидатор билетов Zendesk'
    notes: null
