title: "Сообщить о граффити\_– отказ от прав"
description: 'Позволяет владельцу собственности или его заместителю утвердить отказ от исправления граффити для своей собственности и обновить связанный тикет Zendesk.'
elements: |
  waiver_introduction_text:
    '#markup': '<p>Для проведения работ по исправлению граффити городу Портленд требуется ваше одобрение. Пожалуйста, просмотрите и заполните эту форму.<br /><br /> Набухание и облегчение урны. Phasellus in tempus nisl, eget vulputate nibh. Sed vestibulum ullamcorper neque at imperdiet. Etiam molestie eget ante eu pharetra. In eget auctor lacus. Morbi vel finibus tellus, quis dictum leo. Proin at rhoncus tortor, in consectetur nisl.</p><p> Praesent sucipit libero turpis. Donec et sollicitudin tortor. Mauris semper semper risus, quis faucibus lectus tristique eget. Nullam in nulla malesuada, bibendum turpis at, sagittis quam.</p>'
  property_type:
    '#title': 'Тип недвижимости'
    '#other__option_label': 'Что-то другое...'
    '#other__placeholder': 'Пожалуйста, опишите...'
  property_address:
    '#title': 'Адрес объекта'
  section_contact:
    '#title': 'Ваши Контактные Данные'
  contact_name:
    '#title': Имя
  contact_email:
    '#title': 'Эл. адрес'
  section_waiver:
    '#title': 'Отказ и согласие'
  waiver_text:
    '#markup': '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nisl magna, placerat non nulla nec, vehicula vestibulum elit. Vivamus sed fringilla massa.</p><ol><li> Маурис в pellentesque sapien. Nullam quis tellus eget metus vulputate volutpat.</li><li> Proin fermentum commodo metus, блестящий лео efficitur et. Phasellus gravida veltellus vitae dignissim.</li><li> Набухание и облегчение урны. Phasellus in tempus nisl, eget vulputate nibh. Sed vestibulum ullamcorper neque at imperdiet. Etiam molestie eget ante eu pharetra. In eget auctor lacus.</li><li> Morbi vel finibus tellus, quis dictum leo. Proin at rhoncus tortor, in consectetur nisl.</li></ol><p> Praesent sucipit libero turpis. Donec et sollicitudin tortor. Mauris semper semper risus, quis faucibus lectus tristique eget. Nullam in nulla malesuada, bibendum turpis at, sagittis quam.</p>'
  waiver_agreement:
    '#title': 'Я согласен'
  public_records_statement_standard:
    '#markup': 'Информация, которую вы предоставляете городским властям, является общедоступной и может подлежать обнародованию в соответствии с <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">Законом штата Орегон о государственных записях</a> . Этот закон классифицирует определенную информацию как доступную для общественности по запросу. См. наше <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">заявление о конфиденциальности</a> для получения дополнительной информации.'
  report_ticket_id:
    '#title': 'Идентификатор обращения в службу поддержки'
  original_submission_key:
    '#title': 'Исходный ключ отправки'
  actions:
    '#title': 'Кнопка(и) Отправить'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: 'Отправить другой отчет'
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_ticket_validator:
    label: 'Валидатор билетов Zendesk'
    notes: null
  zendesk_update_ticket:
    label: 'Заявка на обновление Zendesk'
    notes: null
