label: 'Учасники групи'
display:
  default:
    display_title: Головне
    display_options:
      title: Учасники
      fields:
        name:
          label: Користувач
          separator: ', '
        group_roles:
          label: Ролі
          separator: ', '
        changed:
          label: Оновлено
          separator: ', '
        created:
          label: Зареєстрований
          separator: ', '
        edit_group_content:
          text: 'Edit membership'
        delete_group_content:
          text: 'Видалити учасника'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
            first: '« Перша'
            last: 'Остання »'
          expose:
            items_per_page_label: 'Елементів на сторінку'
            items_per_page_options_all_label: '- Усе -'
            offset_label: Зміщення
      exposed_form:
        options:
          submit_button: Застосувати
          reset_button_label: Скинути
          exposed_sorts_label: 'Впорядкувати за'
          sort_asc_label: Зрост
          sort_desc_label: Спад
      arguments:
        gid:
          exception:
            title: Все
          title: 'Manage {{ arguments.gid|placeholder }} members'
  page_1:
    display_title: Сторінка
    display_options:
      menu:
        title: Учасники
