label: 'Термін таксономії'
description: 'Матеріали, що стосуються певного терміну таксономії.'
display:
  default:
    display_title: Головне
    display_options:
      exposed_form:
        options:
          submit_button: Застосувати
          reset_button_label: Скинути
          exposed_sorts_label: 'Впорядкувати за'
          sort_asc_label: Зрост
          sort_desc_label: Спад
  feed_1:
    display_title: Канал
  page_1:
    display_title: Сторінка
