adding:
  advanced_settings:
    gtm:
      GTM-5DGTRSB:
        environment_id: env-1
        environment_token: gX0sWBBfUHwzWER-y90CyQ
removing:
  advanced_settings:
    gtm:
      GTM-5DGTRSB:
        environment_id: env-25
        environment_token: 4_Vhr5UvXjiU9jR6FObiVw
