theme: cloudy
defaults:
  sender: sendgrid_integration
  formatter: webform_php_mail
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  sendgrid_integration:
    none:
      formatter: sendgrid_integration
  rules:
    none:
      formatter: mime_mail
