name: 'Búsqueda superior'
description: 'Principales búsquedas seleccionadas que aparecen debajo de la barra de búsqueda en la página de inicio. Se pueden programar para que solo aparezcan cuando sean relevantes.'
help: null
