label: Monitorizare
description: 'Mesaje recente din jurnal'
display:
  default:
    display_title: Implicit
    display_options:
      title: 'Mesaje recente din jurnal'
      fields:
        nothing:
          admin_label: Pictogramă
        wid:
          label: WID
        severity:
          label: Gravitate
        type:
          label: Tip
        timestamp:
          label: Data
        message:
          label: Mesaj
        name:
          label: Utilizator
          separator: ', '
        link:
          label: Operațiuni
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      exposed_form:
        options:
          submit_button: Filtru
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      empty:
        area:
          admin_label: 'Nu este disponibil niciun mesaj log.'
          content: 'Nu este disponibil niciun mesaj log.'
      filters:
        type:
          expose:
            label: Tip
        severity:
          expose:
            label: Gravitate
  page:
    display_title: Pagina
