label: Glosar
description: 'Tot conținutul, după litere.'
display:
  default:
    display_title: Implicit
    display_options:
      fields:
        title:
          label: Titlu
        name:
          label: Autor
        changed:
          label: 'Ultima actualizare'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
  attachment_1:
    display_title: Anexă
  page_1:
    display_title: Pagina
    display_options:
      menu:
        title: Glosar
