label: 'Conținut recent'
description: 'Conținut recent.'
display:
  default:
    display_title: Implicit
    display_options:
      title: 'Conținut recent'
      fields:
        changed:
          separator: ', '
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      empty:
        area_text_custom:
          content: 'Nu este conținut disponibil.'
      use_more_text: 'Mai multe'
  block_1:
    display_title: Bloc
