label: Arhivă
description: 'Tot conținutul, după lună.'
display:
  default:
    display_title: Implicit
    display_options:
      title: 'Arhivă lunară'
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      arguments:
        created_year_month:
          title: '{{ arguments.created_year_month }}'
  block_1:
    display_title: Bloc
    display_options:
      arguments:
        created_year_month:
          title: '{{ arguments.created_year_month }}'
  page_1:
    display_title: Pagina
