label: 'Blocul Cine este conectat'
description: 'Afișează numele de utilizatori ale celor mai recenți utilizatori activi, precum și numărul total de utilizatori activi.'
display:
  default:
    display_title: Implicit
    display_options:
      title: 'Cine e online'
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      empty:
        area_text_custom:
          content: 'În acest moment sunt 0 utilizatori conectați.'
      filters:
        access:
          expose:
            label: 'Ultima accesare'
            description: 'Un utilizator este considerat online pe această durată de timp după ultima accesare a unei pagini din site.'
      header:
        result:
          content: 'În acest moment sunt @total utilizatori conectați.'
  who_s_online_block:
    display_title: 'Cine e online'
    display_options:
      display_description: 'O listă de utilizatori care sunt, în prezent, autentificați.'
      block_description: 'Cine e online'
