label: 'Cine e nou'
description: 'Afișează o listă a celor mai noi conturi de utilizator de pe site.'
display:
  default:
    display_title: Implicit
    display_options:
      title: 'Cine e nou'
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
  block_1:
    display_title: 'Cine e nou'
    display_options:
      display_description: 'O listă de utilizatori noi'
      block_description: 'Cine e nou'
      block_category: Utilizator
