label: Watchdog
description: 'Mesaje recente din jurnal'
display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Filtru
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
          tags:
            previous: ‹‹
            next: ››
      fields:
        nothing:
          admin_label: Pictogramă
        wid:
          label: WID
        severity:
          label: Gravitate
        type:
          label: Tip
        timestamp:
          label: Data
        message:
          label: Mesaj
        name:
          label: Utilizator
          separator: ', '
        link:
          label: Operaţii
      filters:
        type:
          expose:
            label: Tip
        severity:
          expose:
            label: Gravitate
      title: 'Mesaje recente din jurnal'
      empty:
        area:
          admin_label: 'Nu este disponibil niciun mesaj log.'
          content: 'Nu este disponibil niciun mesaj log.'
  page:
    display_title: Pagina
