display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Aplică
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Descendent
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pe pagină'
            items_per_page_options_all_label: '- Toate -'
            offset_label: Decalaj
          tags:
            previous: '‹ Anterior'
            next: 'Următor ›'
            first: '« Primul'
            last: 'Ultimul »'
      fields:
        status:
          label: Stare
          format_plural_string: !!binary MQNAY291bnQ=
        progress:
          label: Progres
        label:
          label: Etichetă
        item_type:
          label: Tip
          separator: ', '
        word_count:
          separator: ', '
        operations:
          label: Operațiuni
      arguments:
        tltid:
          exception:
            title: Toate
  block_1:
    display_title: Bloc
