label: 'Termen taxonomie'
description: 'Conținut aparținând unui anumit termen dintr-o taxonomie.'
display:
  default:
    display_title: Expert
    display_options:
      exposed_form:
        options:
          submit_button: Aplicare
          reset_button_label: Resetează
          exposed_sorts_label: 'Sortare după'
          sort_asc_label: Ascendent
          sort_desc_label: Desc
  feed_1:
    display_title: Flux
  page_1:
    display_title: Pagina
