settings:
  default_submit_button_label: Trimite
  default_reset_button_label: Resetează
  default_wizard_start_label: Start
  default_wizard_confirmation_label: Finalizat
  default_preview_next_button_label: Previzualizare
  default_preview_label: Previzualizare
  dialog_options:
    narrow:
      title: Îngust
    normal:
      title: Normal
    wide:
      title: Larg
element:
  default_more_title: 'Mai multe'
