label: 'Manage: Group: Members'
display:
  default:
    display_options:
      fields:
        name:
          label: प्रयोगकर्ता
        group_roles:
          label: भूमिका
        edit_group_content:
          text: 'Edit membership'
        delete_group_content:
          text: Remove
      exposed_form:
        options:
          reset_button_label: 'रिसेट गर्नुहोस्'
      arguments:
        gid:
          exception:
            title: सबै
          title: 'Manage {{ arguments.gid|placeholder }} members'
  page_1:
    display_title: पृष्ठ
