third_party_settings:
  toc_js:
    title: 'Trong bài viết này'
    back_to_top_label: 'Trở lại đầu trang'
name: 'Tin tức'
description: 'Tin tức là nội dung theo trình tự thời gian nhằm thông báo cho cộng đồng về các chương trình và truyền đạt các ưu tiên của các văn phòng và các quan chức được bầu. Tin tức có thể được "giới thiệu" trên các trang chủ của nhóm. Loại nội dung tin tức có thể được sử dụng để tạo các bài báo, bài đăng trên blog, thông cáo báo chí và thông báo công khai.'
help: null
