third_party_settings:
  toc_js:
    title: 'Mục lục'
    back_to_top_label: 'Trở lại đầu trang'
name: 'Biến cố'
description: 'Một sự kiện được tổ chức vào một ngày và giờ cụ thể — trừ khi đó là một sự kiện cả ngày. Một sự kiện có thể có một địa điểm tùy ý và có thể cần truyền tải thông tin về cách tham gia vào sự kiện. Sự kiện giúp các chương trình, quan chức và văn phòng tương tác với cộng đồng.'
help: null
