name: 'Thông báo'
description: 'Thông báo giúp thông báo cho cộng đồng những thông tin quan trọng mà cơ quan hoặc văn phòng muốn làm nổi bật trong một khoảng thời gian giới hạn. Họ có thể bị loại bỏ bởi một thành viên cộng đồng.'
help: null
