display:
  default:
    display_title: Chính
    display_options:
      exposed_form:
        options:
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
          tags:
            previous: ‹‹
            next: ››
      fields:
        media_bulk_form:
          action_title: 'Thao tác'
      filters:
        status:
          group_info:
            label: 'Đã công bố'
        name:
          expose:
            label: Tên
        langcode:
          expose:
            label: 'Ngôn ngữ'
      sorts:
        created:
          expose:
            label: 'Từ mới đến cũ'
      title: 'Phương tiện'
      empty:
        area_text_custom:
          content: 'Không có phương tiện nào.'
  page:
    display_title: Trang
    display_options:
      fields:
        media_bulk_form:
          action_title: 'Thao tác'
        edit_media:
          text: Sửa
        delete_media:
          text: Xóa
  widget:
    display_title: Widget
    display_options:
      arguments:
        bundle:
          exception:
            title: 'Tất cả'
      header:
        display_link_grid:
          label: Lưới
        display_link_table:
          label: Bảng
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: 'Ảnh thu nhỏ'
        name:
          label: Tên
        uid:
          label: 'Tác giả'
        changed:
          label: 'Đã cập nhật'
      arguments:
        bundle:
          exception:
            title: 'Tất cả'
      header:
        display_link_grid:
          label: Lưới
        display_link_table:
          label: Bảng
