label: 'Số phiếu bầu'
description: null
display:
  default:
    display_title: 'Bậc thầy'
    display_options:
      title: 'Viên chức dân cử'
      fields:
        label:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
      exposed_form:
        options:
          submit_button: 'Ứng dụng'
          reset_button_label: 'Cài lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Mô tả'
      sorts:
        field_commissioner_number_value:
          admin_label: null
          expose:
            label: null
        label:
          admin_label: null
          expose:
            label: null
      filters:
        type:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
        langcode:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
  all_elected_reference:
    display_title: 'Tham chiếu tất cả các phiếu bầu'
    display_options:
      display_description: null
  entity_reference_1:
    display_title: 'Tham chiếu số phiếu bầu đang hoạt động'
    display_options:
      fields:
        label:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
      filters:
        type:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
        field_active_elected_official_value:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
        langcode:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
      display_description: null
  voting_elected_reference:
    display_title: 'Tham chiếu Bầu chọn Bầu cử'
    display_options:
      filters:
        type:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
        field_voting_council_member_value:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
        langcode:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
      display_description: null
