label: 'Bản đồ địa lý'
description: null
display:
  default:
    display_title: 'Bậc thầy'
    display_options:
      title: 'Bản đồ'
      fields:
        title:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
        field_geo_map:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
      exposed_form:
        options:
          submit_button: 'Ứng dụng'
          reset_button_label: 'Cài lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Mô tả'
      sorts:
        created:
          admin_label: null
          expose:
            label: null
      arguments:
        nid:
          admin_label: null
          exception:
            title: 'Tất cả các'
          title: null
