label: 'Thực đơn chính thức được bầu chọn'
description: null
display:
  default:
    display_title: 'Bậc thầy'
    display_options:
      title: 'Viên chức dân cử'
      fields:
        field_person_image:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
        field_name:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
        field_official_title:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
        view_group:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          text: 'Xem nhóm'
        nothing:
          admin_label: null
          label: null
      exposed_form:
        options:
          submit_button: 'Ứng dụng'
          reset_button_label: 'Cài lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Mô tả'
      sorts:
        field_commissioner_number_value:
          admin_label: null
          expose:
            label: null
      filters:
        field_active_elected_official_value:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
  mega_menu_block:
    display_options:
      display_description: null
