label: 'Phương tiện'
display:
  default:
    display_title: Chính
    display_options:
      exposed_form:
        options:
          submit_button: Lọc
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
      fields:
        media_bulk_form:
          action_title: 'Thao tác'
        thumbnail__target_id:
          label: 'Ảnh thu nhỏ'
        bundle:
          label: Kiểu
        uid:
          label: 'Tác giả'
        status:
          label: 'Trạng thái'
          settings:
            format_custom_true: 'Đã công bố'
            format_custom_false: 'Đã bỏ công bố'
        changed:
          label: 'Đã cập nhật'
        operations:
          label: 'Thao tác'
      filters:
        bundle:
          expose:
            label: Kiểu
        status:
          expose:
            label: Đúng
          group_info:
            group_items:
              1:
                title: 'Đã công bố'
              2:
                title: 'Đã bỏ công bố'
        langcode:
          expose:
            label: 'Ngôn ngữ'
      title: 'Phương tiện'
      empty:
        area_text_custom:
          content: 'Không có phương tiện nào.'
  media_page_list:
    display_title: 'Phương tiện'
