display:
  default:
    display_title: Chính
    display_options:
      exposed_form:
        options:
          submit_button: Lọc
          reset_button_label: 'Thiết lập lại'
          exposed_sorts_label: 'Sắp xếp theo'
          sort_asc_label: 'Tăng dần'
          sort_desc_label: 'Giảm dần'
      pager:
        options:
          expose:
            items_per_page_label: 'Số mục trên một trang'
            items_per_page_options_all_label: '- Tất cả -'
            offset_label: 'Độ dịch'
          tags:
            previous: ‹‹
            next: ››
      fields:
        path:
          label: 'Đường dẫn'
        count:
          label: 'Số lượng'
        langcode:
          label: 'Ngôn ngữ'
        redirect_404_operations:
          label: 'Thao tác'
      filters:
        path:
          expose:
            label: 'Đường dẫn'
        langcode:
          expose:
            label: 'Ngôn ngữ'
        resolved:
          expose:
            label: 'Đã tính xong'
  page_1:
    display_title: Trang
