title: 'Báo cáo Phân biệt đối xử'
description: null
elements: |
  confidentiality_waiver:
    '#title': 'Từ bỏ bảo mật'
    '#description': 'Chính sách của Thành phố là giữ bí mật thông tin bạn cung cấp trên biểu mẫu này nhằm mục đích thực hiện yêu cầu của bạn. Thành phố cũng sẽ cố gắng giữ bí mật thông tin của bạn trong trường hợp ai đó yêu cầu nó được công bố dưới dạng hồ sơ công khai theo <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text = Under% 20Oregon''s% 20Public% 20Records% 20Law, ủy ban% 20of% 20the% 20Legislative% 20Assembly">Luật Hồ sơ Công cộng</a> của Oregon. Nếu bạn muốn từ bỏ tính bảo mật này, vui lòng chọn tùy chọn đó bên dưới.'
    '#options':
      'I do not waive confidentiality.': 'Tôi <em>không</em> từ bỏ tính bảo mật.'
      'I choose to waive confidentiality.': 'Tôi chọn từ bỏ tính bảo mật.'
  report_discrimination:
    '#title': 'Bạn có muốn khiếu nại về chính sách của Thành phố hoặc hành động được thực hiện bởi một chương trình, nhân viên hoặc nhà thầu của Thành phố vi phạm quyền của bạn và phân biệt đối xử chống lại bạn không?'
    '#options':
      'Yes': 'Có, tôi muốn báo cáo sự phân biệt đối xử'
      'No': 'Không, nhưng tôi muốn yêu cầu một chỗ ở ADA'
  request_ada_accommodation_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Bước tiếp theo</h2><p> Vui lòng yêu cầu thông qua dịch vụ <a href="/311/ada-request">Chỗ ở ADA</a> của Thành phố. Bạn cũng có thể gọi cho chúng tôi theo <a href="tel:+1-503-823-4000">số 503-823-4000</a> hoặc TTY qua Dịch vụ chuyển tiếp Oregon: <a href="tel:711">711</a> . Nhân viên sẵn sàng trợ giúp từ Thứ Hai đến Thứ Sáu, từ 8 giờ sáng đến 5 giờ chiều</p></div>'
  report_how_to_complete:
    '#title': 'Bạn muốn hoàn thành yêu cầu hoặc báo cáo của mình như thế nào?'
    '#options':
      'Call us': 'Gọi cho chúng tôi'
      'We contact you': 'Chúng tôi có thể liên hệ với bạn'
      'Continue online': 'Tiếp tục trực tuyến'
  markup_contact_us_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Bước tiếp theo</h2><p> Vui lòng gọi cho chúng tôi theo số 311, <a href="tel:+15038234000">(503) 823-4000</a> , hoặc <a href="tel:711">711</a> để biết TTY qua Dịch vụ Chuyển tiếp Oregon. Nhân viên làm việc từ Thứ Hai đến Thứ Sáu, từ 8 giờ sáng đến 5 giờ chiều, trừ các ngày Lễ của Liên bang.</p></div>'
  report_discrimination_basis:
    '#title': 'Tôi tin rằng sự phân biệt đối xử mà tôi đã trải qua là do ...'
    '#description': '(Đánh dấu vào tất cả các câu phù hợp)'
  report_discrimination_date:
    '#title': 'Sự phân biệt đối xử xảy ra khi nào?'
  report_discrimination_location:
    '#title': 'Sự phân biệt đối xử xảy ra ở đâu?'
    '#location_type__title': 'Vấn đề nằm ở loại tài sản nào?'
    '#location_park_container__title': 'Vùng chứa danh sách công viên'
    '#waterway_instructions__title': 'Hướng dẫn đường thủy'
    '#location_private_owner__title': 'Bạn có phải là chủ sở hữu của tài sản?'
    '#location_address__title': 'Địa chỉ hoặc đường chéo'
    '#location_map__title': 'Bản đồ địa điểm'
    '#suggestions_modal__title': 'Gợi ý'
    '#status_modal__title': 'Chỉ báo trạng thái'
    '#place_name__title': 'Tên địa điểm'
    '#location_details__title': 'Chi tiết vị trí'
    '#location_lat__title': 'Vĩ độ'
    '#location_lon__title': 'Kinh độ'
    '#location_asset_id__title': 'ID nội dung'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  report_discrimination_bureau_office_etc:
    '#title': 'Vui lòng cung cấp tên của văn phòng thành phố, văn phòng, nhân viên, sự kiện hoặc chương trình liên quan đến sự phân biệt đối xử'
  report_discrimination_description:
    '#title': 'Bằng cách nói của riêng bạn, hãy mô tả sự phân biệt đối xử bị cáo buộc.'
    '#description': 'Hãy giải thích điều gì đã xảy ra; ai đã tham gia; chính sách, chương trình hoặc hoạt động nào là phân biệt đối xử (nếu có); tại sao bạn tin rằng điều đó đã xảy ra, và bạn bị phân biệt đối xử như thế nào. Để bảo vệ sự riêng tư của bạn, không bao gồm bất kỳ thông tin cá nhân hoặc liên quan đến sức khỏe.'
  report_discrimination_witnesses:
    '#title': 'Có nhân chứng cho sự phân biệt đối xử không?'
  report_discrimination_witnesses_contact_known:
    '#title': 'Bạn có biết tên và số điện thoại hoặc địa chỉ email của họ không?'
    '#description': 'Nhân chứng sẽ chỉ được liên hệ nếu cần thiết để điều tra khiếu nại của bạn. Nếu được liên hệ, các nhân chứng có thể chọn xem họ có muốn tham gia vào quá trình điều tra hay không.'
  report_discrimination_witness_1_name:
    '#title': 'Tên nhân chứng đầu tiên'
  report_discrimination_witness_1_phone:
    '#title': 'Nhân chứng đầu tiên điện thoại'
  report_discrimination_witness_1_email:
    '#title': 'Email của nhân chứng đầu tiên'
  report_discrimination_add_witness:
    '#title': 'Thêm nhân chứng khác?'
    '#options':
      'Add another witness': 'Thêm một nhân chứng khác'
  report_discrimination_witness_2_name:
    '#title': 'Tên nhân chứng thứ hai'
  report_discrimination_witness_2_phone:
    '#title': 'Nhân chứng thứ hai điện thoại'
  report_discrimination_witness_2_email:
    '#title': 'Email của nhân chứng thứ hai'
  report_discrimination_file_upload:
    '#title': 'Nếu thích hợp, vui lòng đính kèm bất kỳ hình ảnh hoặc tài liệu khác có liên quan đến khiếu nại của bạn.'
  report_discrimination_desired_outcome:
    '#title': 'Bạn muốn xem loại hành động hoặc giải pháp nào được thực hiện?'
  report_discrimination_filed_complaint_other:
    '#title': 'Bạn đã nộp đơn khiếu nại với bất kỳ cơ quan liên bang, tiểu bang hoặc địa phương nào khác, hoặc trong bất kỳ Tòa án Liên bang hoặc Tiểu bang nào chưa?'
    '#description': 'Bạn có quyền nộp đơn lên bất kỳ cơ quan hoặc tòa án nào. Nộp đơn khiếu nại với một cơ quan hoặc tòa án khác không ngăn cản bạn nộp đơn khiếu nại lên Thành phố Portland. Trong một số tình huống nhất định, các cơ quan sẽ phối hợp để đảm bảo cơ quan hoặc tòa án thích hợp điều tra đơn khiếu nại.'
    '#options':
      'Yes': Đúng
      'No': Không
      'Prefer not to answer': 'không thích trả lời'
  report_discrimination_filed_complaint_other_agency:
    '#title': 'Cơ quan hay tòa án nào?'
  report_discrimination_filed_complaint_other_agency_contact_name:
    '#title': 'Người liên hệ của cơ quan hoặc tòa án'
  report_discrimination_filed_complaint_other_agency_contact_phone:
    '#title': 'Điện thoại liên hệ của cơ quan hoặc tòa án'
  report_discrimination_on_behalf_of:
    '#title': 'Bạn đang đưa ra yêu cầu hoặc khiếu nại này cho ai?'
    '#options':
      Myself: 'Riêng tôi'
      'Someone else': 'Một người nào khác'
  report_discrimination_on_behalf_of_name:
    '#title': 'Tên của họ là gì?'
  report_discrimination_on_behalf_of_relationship:
    '#title': 'Mối quan hệ của bạn với họ là gì?'
  report_discrimination_on_behalf_of_permission:
    '#title': 'Bạn đã được họ cho phép để nộp đơn khiếu nại này chưa? Hoặc, bạn có mối quan hệ pháp lý nào cho phép bạn khiếu nại thay mặt họ không?'
  report_discrimination_on_behalf_of_permission_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Bước tiếp theo</h2><p> Vui lòng xin phép họ trước khi gửi biểu mẫu này.</p></div>'
  contact_name:
    '#title': 'Tên của bạn'
  contact_email:
    '#title': E-mail
    '#description': 'Chúng tôi sẽ sử dụng email của bạn để xác nhận nội dung bạn gửi.'
  contact_phone:
    '#title': 'Điện thoại'
  contact_preferred_method:
    '#title': 'Nếu cần, bạn có muốn chúng tôi liên hệ với bạn qua điện thoại hoặc email không?'
    '#options':
      Phone: 'Điện thoại'
      Email: E-mail
  contact_interpreter:
    '#title': 'Bạn có cần thông dịch viên không?'
    '#options':
      'No': Không
      'Yes, VRI (Video Remote Interpretation)': 'Có, VRI (Phiên dịch từ xa bằng video)'
      'Yes, Oregon Relay Service': 'Có, Dịch vụ chuyển tiếp Oregon'
      'Yes, language interpreter': 'Có, thông dịch viên ngôn ngữ'
  contact_language:
    '#title': 'Ngôn ngữ nào?'
  markup_complainant_acknowledgement_text:
    '#markup': '<p><strong>Lời xác nhận của người khiếu nại</strong></p><p> Bằng cách gửi biểu mẫu này, tôi khẳng định rằng (1) Tôi đã đọc, hiểu và chấp nhận các <a href="/code/23">điều khoản về thủ tục theo dõi và điều tra các khiếu nại về Quyền Dân sự</a> và (2) Thông tin tôi cung cấp trong biểu mẫu này là đúng theo hiểu biết của tôi.</p>'
  complainant_acknowledgement_agree:
    '#title': 'tôi đồng ý'
  section_agent_use_only:
    '#title': 'Chỉ sử dụng đại lý'
  agent_email:
    '#title': 'Email đại lý'
    '#default_value': '[current-user: display-name] <[current-user: mail]>'
  agent_ticket_number:
    '#title': 'Vé số'
  agent_action_taken:
    '#title': 'Hành động'
  agent_contact_type:
    '#title': 'Loại liên hệ'
  agent_ticket_type:
    '#title': 'loại vé'
  agent_summary:
    '#title': 'Tóm tắt đại lý'
  report_ticket_id:
    '#title': 'Báo cáo ID vé'
  actions:
    '#title': 'Gửi (các) nút'
    '#submit__label': Nộp
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_new_ticket:
    label: 'Vé mới của Zendesk'
    notes: 'Tạo phiếu khiếu nại về Phân biệt đối xử mới và giao nó cho nhóm 311: ADA và Phân biệt đối xử.'
