title: 'Báo cáo Khiếu nại Xóa bỏ Khu cắm trại'
description: null
elements: |
  section_report:
    '#title': 'Báo cáo'
  report_problem_type:
    '#title': 'Loại sự cố nào xảy ra?'
    '#options':
      'My property was taken.': 'Một số hoặc tất cả tài sản của tôi không được lưu trữ đúng cách.'
      'A City employee or contractor was disrespectful.': 'Một nhân viên hoặc nhà thầu của Thành phố đã thiếu tôn trọng.'
    '#other__option_label': 'Thứ gì khác'
    '#other__placeholder': 'Làm ơn miêu tả.'
  markup_property_collection:
    '#markup': '<div class="alert alert--info next-steps"><h2>Thông tin</h2><p> Nếu bạn đang cố gắng xác định vị trí tài sản của mình, trước tiên hãy gọi <a href="tel:+1-503-387-1336">số 503-387-1336</a> để liên hệ với cơ sở lưu trữ Sạch Sinh học Phản ứng Nhanh. Bạn có thể gọi từ Thứ Hai đến Thứ Sáu từ 9:30 sáng đến 3:30 chiều hoặc Thứ Bảy từ 10:30 sáng đến 2:30 chiều.<br /><br /> Họ cất giữ tất cả tài sản do Thành phố thu được trong thời gian tối thiểu là ba mươi (30) ngày kể từ ngày thu được. <strong data-renderer-mark="true">Nếu tài sản của bạn vẫn bị thiếu, hãy tiếp tục điền vào biểu mẫu này để báo cáo sự cố.</strong></p></div>'
  report_employer:
    '#title': 'Người đó đã làm việc cho ai?'
    '#options':
      'Rapid Response Bio Clean': 'Phản hồi nhanh Bio Clean (nhân viên mặc áo sơ mi đỏ có logo của chương trình ở phía sau) - <img src="https://www.portland.gov/sites/default/files/styles/thumbnail/public/2022/rapidresponsebio-clean.jpg" />'
      'Central City Concern Clean Start Employee': 'Nhân viên của Central City Concern Clean Start Start (nhân viên mặc áo sơ mi màu cam sáng với logo của chương trình ở mặt trước) - <img src="https://www.portland.gov/sites/default/files/styles/thumbnail/public/2022/clean-start-shirt.jpg" />'
      'Portland Bureau of Transportation': 'Cục Giao thông vận tải Portland'
      'Portland Fire & Rescue': 'Cứu hỏa & Cứu hộ Portland'
      'Portland Police Bureau': 'Cục cảnh sát Portland'
  markup_ombudsman:
    '#markup': '<div class="alert alert--info next-steps"><h2>Bước tiếp theo</h2><p> Vui lòng nộp đơn khiếu nại của bạn với <a href="https://www.portland.gov/ombudsman/make-complaint-about-city-bureau-or-office">Thanh tra viên Thành phố Portland</a> .</p></div>'
  markup_ipr:
    '#markup': '<div class="alert alert--info next-steps"><h2>Bước tiếp theo</h2><p> Vui lòng nộp đơn khiếu nại của bạn cho <a href="https://www.portland.gov/ipr/submit-complaint-or-commendation-about-police">Ban Đánh giá Cảnh sát Độc lập</a> .</p></div>'
  report_date:
    '#title': 'Sự cố xảy ra khi nào?'
  report_location:
    '#title': 'Vụ việc xảy ra ở đâu?'
    '#location_type__title': 'Vụ việc xảy ra ở đâu?'
    '#location_address__title': 'Vụ việc xảy ra ở đâu?'
    '#location_park_container__title': 'Vùng chứa danh sách công viên'
    '#waterway_instructions__title': 'Hướng dẫn đường thủy'
    '#location_private_owner__title': 'Bạn có phải là chủ sở hữu của tài sản không?'
    '#location_map__title': 'Bản đồ địa điểm'
    '#suggestions_modal__title': 'Gợi ý'
    '#status_modal__title': 'Chỉ báo trạng thái'
    '#place_name__title': 'Tên địa điểm'
    '#location_details__title': 'Chi tiết vị trí'
    '#location_lat__title': 'Vĩ độ'
    '#location_lon__title': 'Kinh độ'
    '#location_asset_id__title': 'ID nội dung'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  report_description:
    '#title': 'Bằng cách nói của riêng bạn, hãy mô tả sự việc. Vui lòng giải thích điều gì đã xảy ra, ai có liên quan và bất kỳ tài sản nào bị lấy đi và không được cất giữ đúng cách.'
    '#description': 'Để bảo vệ sự riêng tư của bạn, <strong>không</strong> bao gồm bất kỳ thông tin cá nhân hoặc liên quan đến sức khỏe.'
  report_has_witnesses:
    '#title': 'Có nhân chứng cho vụ việc không?'
    '#options':
      'Yes': Đúng
      'No': Không
  report_known_witnesses:
    '#title': 'Bạn có biết tên và số điện thoại hoặc địa chỉ email của họ không?'
    '#description': 'Nhân chứng sẽ chỉ được liên hệ nếu cần thiết để điều tra khiếu nại của bạn. Nếu được liên hệ, nhân chứng có thể chọn xem họ có muốn tham gia hay không.'
    '#options':
      'Yes': Đúng
      'No': Không
  report_witness1_name:
    '#title': 'Tên nhân chứng đầu tiên'
  report_witness1_phone:
    '#title': 'Điện thoại của nhân chứng đầu tiên'
  report_witness1_email:
    '#title': 'Email của nhân chứng đầu tiên'
  report_witness2_name:
    '#title': 'Tên nhân chứng thứ hai'
  report_witness2_phone:
    '#title': 'Điện thoại nhân chứng thứ hai'
  report_witness2_email:
    '#title': 'Email nhân chứng thứ hai'
  report_photo:
    '#title': 'Nếu thích hợp, vui lòng đính kèm bất kỳ hình ảnh hoặc tài liệu khác có liên quan đến khiếu nại của bạn.'
  section_contact:
    '#title': 'thông tin liên lạc của bạn'
  contact_name:
    '#title': Tên
  contact_email:
    '#title': E-mail
    '#description': 'Chúng tôi sẽ sử dụng email của bạn để xác nhận nội dung bạn gửi.'
  contact_phone:
    '#title': 'Điện thoại'
    '#description': 'Vui lòng cung cấp số điện thoại của bạn trong trường hợp chúng tôi cần thêm thông tin.'
  contact_preference:
    '#title': 'Nếu cần, bạn có muốn chúng tôi liên hệ với bạn qua điện thoại hoặc email không?'
    '#options':
      Phone: 'Điện thoại'
      Email: E-mail
  section_public_records_statement:
    '#title': 'Tuyên bố Hồ sơ Công cộng'
  public_records_statement_standard:
    '#markup': 'Thông tin bạn cung cấp cho Thành phố là một hồ sơ công khai và có thể được tiết lộ theo <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text = Under% 20Oregon''s% 20Public% 20Records% 20Law, ủy ban% 20of% 20the% 20Legislative% 20Assembly">Luật Hồ sơ Công cộng</a> của Oregon. Luật này phân loại thông tin nhất định là có sẵn cho công chúng theo yêu cầu. Xem <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">tuyên bố về quyền riêng tư</a> của chúng tôi để biết thêm thông tin.'
  actions:
    '#title': 'Gửi (các) nút'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: 'Đơn khiếu nại đã nộp'
  confirmation_message: 'Cảm ơn bạn đã cung cấp cho chúng tôi thông tin này. Một nhân viên từ Chương trình Giảm thiểu Tác động của Thành phố Portland sẽ liên hệ với bạn trong vòng 14 ngày làm việc. Nếu bạn muốn cung cấp thêm thông tin về khiếu nại của mình, vui lòng gửi email đến <a href="mailto:reportpdx@portlandoregon.gov">reportpdx@portlandoregon.gov</a> .'
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  submit_report_to_reportpdx:
    label: 'Gửi báo cáo đến reportpdx@portlandoregon.gov'
    notes: null
    settings:
      from_name: null
      reply_to: null
      return_path: null
      sender_name: null
      subject: '_mặc định'
      body: '<p>Đã gửi trên [webform_submission: created]</p><p> Giá trị đã gửi là:</p> [webform_submission: giá trị]'
