title: 'Báo cáo một E-Scooter - Độ phân giải'
description: 'Được sử dụng bởi các đại lý của công ty xe tay ga để báo cáo việc giải quyết các vấn đề do các thành viên cộng đồng đệ trình. Một liên kết đến biểu mẫu này, bao gồm các giá trị chuỗi truy vấn cho tập hợp trước của các trường, được gửi đến công ty xe tay ga cho mỗi báo cáo.'
category: 'Nghị quyết'
elements: |
  report_issue:
    '#title': 'Vấn đề với e-scooter là gì?'
    '#options':
      'improperly parked': 'E-scooter đỗ không đúng cách'
      damaged: 'E-scooter bị hỏng hoặc hoạt động không chính xác'
      'riding on sidewalk': 'Người dùng đang đi trên vỉa hè'
    '#other__option_label': 'Thứ gì khác...'
    '#other__placeholder': 'Làm ơn miêu tả...'
  report_blocking:
    '#title': 'Xe tay ga điện tử có đang chặn vỉa hè, đường nhỏ, làn đường dành cho xe đạp, đường lái xe vào, đường phố, điểm dừng phương tiện công cộng hoặc loại làn đường giao thông khác không?'
  report_private_property:
    '#title': 'Xe tay ga điện tử có được đậu trên tài sản tư nhân không?'
  issue_resolution:
    '#title': 'Giải quyết vấn đề'
    '#options':
      'Scooter has been moved': 'Xe tay ga đã được di chuyển'
      'Scooter has been taken in for repairs': 'Xe tay ga đã được đưa vào sửa chữa'
      'Scooter has been fixed on location': 'Xe tay ga đã được cố định về vị trí'
      'Upon inspection, scooter does not appear to be out of compliance': 'Khi kiểm tra, xe tay ga có vẻ không phù hợp'
      'Incorrect e-scooter company selected by community member': 'Công ty xe tay ga điện tử do thành viên cộng đồng chọn không chính xác - Vui lòng chọn đúng công ty bên dưới. Vé sẽ được định tuyến lại.'
    '#other__option_label': 'Thứ gì khác...'
    '#other__placeholder': 'Làm ơn miêu tả...'
  report_company:
    '#title': 'Công ty xe điện (e-scooter)'
    '#description': 'Xe tay ga thuộc hãng xe điện nào? Hoặc, e-scooter có màu gì?'
    '#options':
      Bird: 'Chim (đen)'
      Bolt: 'Bu lông (đen và vàng)'
      Lime: 'Vôi (xanh)'
      Spin: 'Spin (cam)'
      'Not sure': 'Không chắc'
  report_asset_id:
    '#title': 'ID xe tay ga điện tử'
  report_ticket_id:
    '#title': 'ID vé hỗ trợ'
    '#description': 'Nếu bạn nhấp vào liên kết giải quyết trong email thông báo mà chúng tôi đã gửi, giá trị này sẽ được nhập tự động.'
  company_rep_id:
    '#title': 'Đại diện công ty'
    '#description': 'Vui lòng nhập tên, tên viết tắt hoặc số nhận dạng duy nhất của bạn trong trường hợp có câu hỏi về giải pháp báo cáo này.'
  original_submission_key:
    '#title': 'Khóa gửi ban đầu'
  actions:
    '#title': 'Gửi (các) nút'
    '#submit__label': Nộp
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: 'Vé đã được cập nhật'
  confirmation_message: 'Cảm ơn bạn đã gửi báo cáo giải pháp của bạn. Phản hồi của bạn đã được ghi lại và vé đã được cập nhật.'
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  resolve_ticket:
    label: 'Giải quyết vé'
    notes: null
  reroute_ticket:
    label: 'Định tuyến lại vé'
    notes: 'Định tuyến lại một vé đến một công ty khác nếu thành viên cộng đồng chọn công ty không chính xác.'
  zendesk_ticket_validator:
    label: 'Trình xác thực vé Zendesk'
    notes: null
