title: 'Báo cáo Graffiti - Miễn trừ'
description: 'Cho phép chủ sở hữu tài sản hoặc người đại diện của họ phê duyệt từ bỏ việc khắc phục hình graffiti đối với tài sản theri và cập nhật vé Zendesk liên quan'
elements: |
  waiver_introduction_text:
    '#markup': '<p>Để thực hiện công việc sửa chữa graffiti, Thành phố Portland cần sự chấp thuận của bạn. Vui lòng xem lại và hoàn thành biểu mẫu này.<br /><br /> Fusce tại tiện ích mở rộng urna. Phasellus trong tempus nisl, eget vulputate nibh. Sed vestibulum ullamcorper neque ở bất toàn. Etiam moltie eget ante eu pharetra. Trong eget auctor lacus. Morbi vel finibus tellus, quis dictum leo. Proin ở rhoncus rùa, ở consectetur nisl.</p><p> Kơ-nia suscipit libero turpis. Donec et sollicitudin tra tấn. Mauris semper semper risus, quis faucibus lectus tristique eget. Nullam trong nulla malesuada, bibendum turpis at, sagittis quam.</p>'
  property_type:
    '#title': 'Loại tài sản'
    '#other__option_label': 'Thứ gì khác...'
    '#other__placeholder': 'Làm ơn miêu tả...'
  property_address:
    '#title': 'Địa chỉ tài sản'
  section_contact:
    '#title': 'thông tin liên lạc của bạn'
  contact_name:
    '#title': Tên
  contact_email:
    '#title': E-mail
  section_waiver:
    '#title': 'Miễn trừ và Thỏa thuận'
  waiver_text:
    '#markup': '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nisl magna, giả dược không nulla chưa được xác định, vi khuẩn lạc chỗ và elit. Vivamus sed fringilla massa.</p><ol><li> Mauris trong sapien tuyệt đẹp. Nullam quis tellus eget metus vulputate volutpat.</li><li> Proin lên men hàng hóa metus, một scelerisque leo efficitur et. Phasellus gravida vel tellus vitae dignissim.</li><li> Fusce tại tiện ích mở rộng urna. Phasellus trong tempus nisl, eget vulputate nibh. Sed vestibulum ullamcorper neque ở bất toàn. Etiam moltie eget ante eu pharetra. Trong eget auctor lacus.</li><li> Morbi vel finibus tellus, quis dictum leo. Proin ở rhoncus rùa, ở consectetur nisl.</li></ol><p> Kơ-nia suscipit libero turpis. Donec et sollicitudin tra tấn. Mauris semper semper risus, quis faucibus lectus tristique eget. Nullam trong nulla malesuada, bibendum turpis at, sagittis quam.</p>'
  waiver_agreement:
    '#title': 'Tôi đồng ý'
  public_records_statement_standard:
    '#markup': 'Thông tin bạn cung cấp cho Thành phố là một hồ sơ công khai và có thể được tiết lộ theo <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text = Under% 20Oregon''s% 20Public% 20Records% 20Law, ủy ban% 20of% 20the% 20Legislative% 20Assembly">Luật Hồ sơ Công cộng</a> của Oregon. Luật này phân loại thông tin nhất định là có sẵn cho công chúng theo yêu cầu. Xem <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">tuyên bố về quyền riêng tư</a> của chúng tôi để biết thêm thông tin.'
  report_ticket_id:
    '#title': 'ID vé hỗ trợ'
  original_submission_key:
    '#title': 'Khóa gửi ban đầu'
  actions:
    '#title': 'Gửi (các) nút'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: 'Gửi báo cáo khác'
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_ticket_validator:
    label: 'Trình xác thực vé Zendesk'
    notes: null
  zendesk_update_ticket:
    label: 'Vé cập nhật Zendesk'
    notes: null
