title: 'Liên hệ với một quan chức được bầu cử'
description: 'Được sử dụng để gửi phản hồi trực tiếp đến các quan chức được bầu và yêu cầu các cuộc họp.'
category: null
elements: |
  introductory_text:
    '#markup': '<p>Cung cấp phản hồi về chính sách hoặc hành động của Thành phố Portland hoặc yêu cầu một cuộc họp với thị trưởng, ủy viên thành phố, hoặc kiểm toán viên thành phố.</p>'
  purpose:
    '#title': 'Bạn thích làm gì?'
    '#options':
      provide_feedback_council: 'Cung cấp nhận xét hoặc phản hồi về một chủ đề cho các thành viên Hội đồng thành phố'
      provide_feedback: 'Cung cấp nhận xét hoặc phản hồi về một chủ đề cho tất cả các quan chức được bầu cử của thành phố'
      provide_feedback_specific_elected: 'Cung cấp nhận xét hoặc phản hồi cho các quan chức được bầu cụ thể'
      request_meeting: 'Yêu cầu một cuộc họp với một quan chức được bầu cử hoặc yêu cầu họ phát biểu tại một sự kiện'
      provide_testimony: 'Cung cấp lời khai về một mục sắp tới trong chương trình làm việc'
  section_provide_testimony:
    '#title': 'Cung cấp lời khai về một mục sắp tới trong chương trình làm việc'
  testimony_instructions:
    '#markup': 'Lời khai bằng văn bản có thể được nộp cho các mục cụ thể trong chương trình nghị sự. Lời khai sẽ được chia sẻ với Hội đồng Thành phố và nhân viên. Nó sẽ được đưa vào hồ sơ công khai theo <a href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon%27s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">Luật Hồ sơ Công cộng</a> của Oregon.<br /><br /> Gửi lời khai bằng văn bản qua email tại <a href="mailto:cctestimony@portlandoregon.gov">cctestimony@portlandoregon.gov</a> .<br /><br /> <a href="/council/agenda">Xem chương trình làm việc sắp tới</a>'
  section_provide_feedback:
    '#title': 'Cung cấp nhận xét hoặc phản hồi về một chủ đề cho tất cả các quan chức được bầu cử của thành phố'
  elected_officials_feedback_title:
    '#markup': '<h2>Cung cấp nhận xét hoặc phản hồi về một chủ đề cho tất cả các quan chức được bầu cử của thành phố</h2>'
  markup:
    '#markup': '<h2>Cung cấp nhận xét hoặc phản hồi về một chủ đề cho các thành viên Hội đồng thành phố</h2>'
  feedback_topics_entity:
    '#title': 'Chọn một hoặc nhiều chủ đề thích hợp'
  feedback_topic_other:
    '#title': 'Chủ đề khác không được liệt kê ở trên'
  feedback_recipients_entity_all:
    '#title': 'Chúng tôi nên gửi bình luận hoặc phản hồi của bạn cho ai'
    '#options_all_text': 'tôi không chắc'
  section_request_meeting:
    '#title': 'Yêu cầu một cuộc họp với một quan chức được bầu cử hoặc yêu cầu họ phát biểu tại một sự kiện'
  meeting_recipients_entity:
    '#title': 'Chúng tôi nên gửi yêu cầu của bạn cho ai?'
  meeting_event_type:
    '#title': 'Bạn muốn mời họ đến những gì?'
    '#options':
      'Attend an event': 'Tham dự một sự kiện'
      'Speak at an event': 'Nói chuyện tại một sự kiện'
      'Speak at a meeting': 'Nói chuyện trong một cuộc họp'
      'Meet with me or my group': 'Gặp gỡ với tôi hoặc nhóm của tôi'
  meeting_title:
    '#title': 'Sự kiện hoặc tiêu đề cuộc họp'
  meeting_description:
    '#title': 'Mô tả sự kiện / cuộc họp'
    '#description': '<p data-renderer-start-pos="2355">Vui lòng cung cấp bản tóm tắt ngắn gọn về sự kiện / cuộc họp, địa điểm, mục đích, đối tượng, số lượng người sẽ tham dự và bất kỳ chi tiết quan trọng nào khác.</p>'
  meeting_preferred_datetime:
    '#title': 'Ngày và giờ họp ưu tiên'
  meeting_alternate_datetime:
    '#title': 'Ngày và giờ cuộc họp thay thế'
  meeting_duration:
    '#title': 'Bạn yêu cầu bao nhiêu thời gian?'
    '#options':
      '15 minutes or less': '15 phút trở xuống'
      '30 minutes': '30 phút'
      '1 hour': '1 giờ'
      'More than 1 hour': 'Hơn 1 giờ'
  meeting_phone:
    '#title': 'Số điện thoại'
    '#description': 'Vui lòng cung cấp số điện thoại của bạn để chúng tôi liên hệ và đặt lịch theo yêu cầu của bạn nếu được chấp thuận.'
  section_feedback_specific_official:
    '#title': 'Cung cấp nhận xét hoặc phản hồi cho các quan chức được bầu cụ thể'
  feedback_recipients_entity:
    '#title': 'Chúng tôi nên gửi nhận xét hoặc phản hồi của bạn cho ai (chọn tất cả các câu phù hợp)'
    '#options_all_text': 'tôi không chắc'
  feedback_specific_not_sure:
    '#title': 'Không chắc chắn'
  feedback_specific_official_link:
    '#markup': '<a href="/elected-officials">Xem các nhiệm vụ của văn phòng hiện tại của chính thức</a>'
  feedback_comments:
    '#title': 'Bạn muốn nói gì?'
    '#description': '<p data-pm-slice="1 1 []">Nhận xét và phản hồi súc tích rõ ràng được đánh giá cao.</p>'
  section_contact_information:
    '#title': 'thông tin liên lạc của bạn'
  contact_name:
    '#title': Tên
  contact_email_address:
    '#title': 'Địa chỉ email'
  contact_country:
    '#title': 'Quốc gia'
  contact_street_address:
    '#title': 'Địa chỉ đường phố'
  contact_unit_type:
    '#title': 'Loại đơn vị'
  contact_unit_number:
    '#title': 'Số đơn vị'
  contact_city:
    '#title': 'Thành phố'
  contact_state:
    '#title': 'Tiểu bang'
  contact_postal_code:
    '#title': 'Mã ZIP / Mã bưu điện'
  contact_international_address:
    '#title': 'Địa chỉ Bưu điện Quốc tế'
  section_public_records_statement:
    '#title': 'Tuyên bố Hồ sơ Công cộng'
  public_records_statement_text:
    '#markup': 'Thông tin bạn cung cấp cho Thành phố là một hồ sơ công khai và có thể được tiết lộ theo <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text = Under% 20Oregon''s% 20Public% 20Records% 20Law, ủy ban% 20of% 20the% 20Legislative% 20Assembly">Luật Hồ sơ Công cộng</a> của Oregon. Luật này phân loại thông tin nhất định là có sẵn cho công chúng theo yêu cầu. Xem <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">tuyên bố về quyền riêng tư</a> của chúng tôi để biết thêm thông tin.'
  voting_electeds_entity:
    '#title': 'Bỏ phiếu bầu cử'
  computed_recipient_list:
    '#title': 'Danh sách người nhận'
  computed_subject:
    '#title': 'Môn học'
  computed_confirmation_message:
    '#title': 'Tin nhắn xác nhận được tính toán'
  actions:
    '#title': 'Gửi (các) nút'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: 'Cảm ơn bạn đã gửi'
  confirmation_message: '[webform_submission: giá trị: computed_confirmation_message: htmldecode]<br />'
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  email_2:
    label: 'Gửi email đến những người được bầu chọn đã chọn'
    notes: null
    settings:
      from_name: null
      reply_to: null
      return_path: null
      sender_name: null
      subject: null
      body: null
