settings:
  default_submit_button_label: 'Gửi đi'
  default_reset_button_label: 'Thiết lập lại'
  default_wizard_prev_button_label: '< Trang trước'
  default_wizard_next_button_label: 'Trang sau >'
  default_wizard_start_label: 'Khởi động'
  default_wizard_confirmation_label: 'Hoàn thành'
  default_preview_next_button_label: 'Xem trước'
  default_preview_prev_button_label: '< Trước'
  default_preview_label: 'Xem trước'
  default_draft_button_label: 'Lưu bản nháp'
  dialog_options:
    normal:
      title: 'Bình thường'
element:
  default_more_title: Thêm
