title: 'Báo cáo Graffiti'
description: 'Báo cáo graffiti về tài sản công hoặc yêu cầu hỗ trợ xóa đối với tài sản tư nhân'
elements: |
  section_report:
    '#title': 'Báo cáo'
  report_location:
    '#title': 'Địa điểm'
    '#default_value':
      location_type: 'đường phố'
      location_park: null
      location_address: null
      place_name: null
      location_details: null
      location_lat: null
      location_lon: null
      location_private_owner: null
    '#location_map__description': '<em>Các báo cáo graffiti hiện tại được hiển thị bằng điểm đánh dấu màu đỏ <img src="/modules/custom/portland/modules/portland_location_picker/images/map_marker_incident.png" alt="Biểu tượng đánh dấu bản đồ màu đỏ" class="inline-icon"> khi bản đồ được phóng to hoàn toàn. Các báo cáo mới phải được xem xét và có thể mất đến 2 ngày làm việc để xuất hiện trên bản đồ.</em>'
    '#location_type__title': 'Vấn đề nằm ở loại tài sản nào?'
    '#location_park_container__title': 'Vùng chứa danh sách công viên'
    '#waterway_instructions__title': 'Hướng dẫn đường thủy'
    '#location_private_owner__title': 'Bạn có phải là chủ sở hữu của tài sản?'
    '#location_address__title': 'Địa chỉ hoặc đường chéo'
    '#location_map__title': 'Bản đồ địa điểm'
    '#suggestions_modal__title': 'Gợi ý'
    '#status_modal__title': 'Chỉ báo trạng thái'
    '#place_name__title': 'Tên địa điểm'
    '#location_details__title': 'Chi tiết vị trí'
    '#location_lat__title': 'Vĩ độ'
    '#location_lon__title': 'Kinh độ'
    '#location_asset_id__title': 'ID nội dung'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  markup_select_to_continue:
    '#markup': 'Thực hiện một lựa chọn để tiếp tục.'
  report_hate_speech_or_gang:
    '#title': 'Lời nói căm thù hoặc băng đảng graffiti này có liên quan đến băng đảng không?'
    '#options':
      'Yes': Đúng
      'No': Không
      'Not sure': 'Không chắc'
  report_property_owner_assistance:
    '#title': 'Bạn muốn yêu cầu gì?'
    '#options':
      Assistance: 'Yêu cầu hỗ trợ xóa graffiti miễn phí hoặc chi phí thấp từ Chương trình Graffiti của Civic Life'
      'Removal Kit': 'Yêu cầu bộ dụng cụ xóa hình vẽ bậy hoặc tìm hiểu thêm về sáng kiến "Dọn dẹp, sơn lại"'
  report_private_property_type:
    '#title': 'Đó là loại tài sản nào?'
  report_corporate_franchise:
    '#title': 'Bạn có phải là một công ty nhượng quyền thương mại?'
  report_business_employees_amt:
    '#title': 'Doanh nghiệp có bao nhiêu nhân viên?'
  report_building_units_amt:
    '#title': 'Tòa nhà / khu phức hợp có bao nhiêu căn?'
  report_nonprofit_employees:
    '#title': 'Tổ chức phi lợi nhuận có bao nhiêu nhân viên?'
  report_contractor_text:
    '#admin_title': 'Không đủ điều kiện'
    '#markup': '<div class="alert alert--info next-steps"><h2>Bạn không đủ điều kiện để được hỗ trợ xóa hình vẽ bậy [đây có phải là ngõ cụt hay chúng tôi vẫn muốn người dùng gửi biểu mẫu?]</h2><p> Thông tin nhà thầu tại đây ...</p></div>'
  report_removal_kit_text:
    '#markup': '<div class="alert alert--info next-steps"><h2>Các bước tiếp theo [chúng tôi muốn điều này là một kết thúc hay để người dùng gửi biểu mẫu?]</h2><p> Đây là cách yêu cầu một bộ ........</p></div>'
  markup_qualifies:
    '#markup': '<div class="alert alert--info next-steps"><h2>Bạn có thể đủ điều kiện để được hỗ trợ xóa hình vẽ bậy</h2><p> Vui lòng tiếp tục điền vào báo cáo này.</p></div>'
  report_tenant_or_neighbor:
    '#title': 'Bạn là hàng xóm hay người thuê nhà?'
    '#options':
      'I am a tenant': 'Tôi là người thuê nhà'
      'I am a neighbor or community member': 'Tôi là hàng xóm hoặc thành viên cộng đồng'
  report_tenant_text:
    '#markup': '<div class="alert alert--info next-steps"><h2>Bước tiếp theo</h2><p> Vui lòng nói chuyện với chủ sở hữu của tài sản.</p></div>'
  report_above_ground_level:
    '#title': 'Hình vẽ bậy có cao hơn mặt đất (cao hơn 8 feet) không?'
    '#options':
      'Yes': Đúng
      'No': Không
      'Not sure': 'Không chắc'
  report_graffiti_on_mural:
    '#title': 'Có phải là graffiti trên một bức tranh tường?'
  report_repeat_offender:
    '#title': 'Bạn đã từng nhìn thấy hình vẽ graffiti hoặc thẻ này trước đây chưa? Nó có phải là từ một người tái phạm không?'
  report_photo:
    '#title': 'Vui lòng tải lên một bức ảnh graffiti'
    '#description': 'Một bức ảnh rõ ràng về hình graffiti giúp chúng tôi xác định loại bề mặt mà nó nằm trên đó và những nguồn lực nào có thể cần thiết để giải quyết vấn đề đó.'
  section_contact:
    '#title': 'thông tin liên lạc của bạn'
  contact_name:
    '#title': Tên
  contact_email:
    '#title': E-mail
    '#description': 'Chúng tôi sẽ sử dụng email của bạn để trả lời phản hồi hoặc yêu cầu của bạn. Nó sẽ không được công bố trong các báo cáo hồ sơ công khai nhưng sẽ được chia sẻ với các nhân viên thành phố.'
  section_public_records_statement:
    '#title': 'Tuyên bố Hồ sơ Công cộng'
  public_records_statement_standard:
    '#markup': 'Thông tin bạn cung cấp cho Thành phố là một hồ sơ công khai và có thể được tiết lộ theo <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text = Under% 20Oregon''s% 20Public% 20Records% 20Law, ủy ban% 20of% 20the% 20Legislative% 20Assembly">Luật Hồ sơ Công cộng</a> của Oregon. Luật này phân loại thông tin nhất định là có sẵn cho công chúng theo yêu cầu. Xem <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">tuyên bố về quyền riêng tư</a> của chúng tôi để biết thêm thông tin.'
  section_agent_use_only:
    '#title': 'Chỉ sử dụng đại lý'
  agent_email:
    '#title': 'Email đại lý'
    '#default_value': '[current-user: display-name] <[current-user: mail]>'
  agent_ticket_number:
    '#title': 'Vé số'
  agent_action_taken:
    '#title': 'Hành động'
    '#options':
      Resolved: 'Đã giải quyết'
      Referred: 'Được giới thiệu'
  admin_contact_type:
    '#title': 'Loại liên hệ'
    '#options':
      Phone: 'Điện thoại'
      'Requested Callback': 'Yêu cầu gọi lại'
      Email: E-mail
      Webform: 'Hình thức web'
      'In Person': 'Mặt đối mặt'
      Webchat: 'Web chat'
      'Social Media': 'Truyền thông xã hội'
  agent_ticket_type:
    '#title': 'loại vé'
    '#options':
      Question: 'Câu hỏi'
      Incident: 'Sự cố'
      Problem: 'Vấn đề'
      Task: 'Nhiệm vụ'
  agent_summary:
    '#title': 'Tóm tắt đại lý'
  computed_priority:
    '#title': 'Quyền ưu tiên'
  actions:
    '#title': 'Gửi (các) nút'
  report_ticket_id:
    '#title': 'ID vé hỗ trợ'
  ticket_description:
    '#title': 'Mô tả vé'
  resolution_url:
    '#title': 'URL phân giải'
  waiver_url:
    '#title': 'URL từ bỏ'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: 'Gửi một báo cáo khác'
  limit_total_message: null
  limit_user_message: null
handlers:
  create_new_zendesk_ticket:
    label: 'Tạo vé Zendesk mới'
    notes: null
