third_party_settings:
  toc_js:
    title: 'En este articulo'
    back_to_top_label: 'Volver arriba'
name: Noticias
description: 'Las noticias son contenido cronológico destinado a informar a la comunidad sobre los programas y comunicar las prioridades de las oficinas y los funcionarios electos. Las noticias se pueden "destacar" en las páginas de inicio de los grupos. El tipo de contenido de noticias se puede utilizar para crear artículos de noticias, publicaciones de blog, comunicados de prensa y avisos públicos.'
help: null
