third_party_settings:
  toc_js:
    title: 目录
    back_to_top_label: 回到顶部
name: 资源
description: '资源是不在 Portland.gov 上托管或无法在 Portland.gov 上编入索引的内容或应用程序，例如搜索视图。资源可用于州、县和都会区服务，以创建带有摘要的搜索结果。资源也可用于创建指向搜索的特色链接。 （例如，Find a Park 是一种资源，因为 /parks/search 上的页面不可用于我们的搜索索引或被推荐。）'
help: null
