label: 公园设施内
description: null
display:
  default:
    display_title: 掌握
    display_options:
      title: 在这个公园设施中
      fields:
        title_1:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
      exposed_form:
        options:
          submit_button: 申请
          reset_button_label: 重置
          exposed_sorts_label: 排序方式
          sort_asc_label: 上升
          sort_desc_label: 描述
      sorts:
        title:
          admin_label: null
          expose:
            label: null
      arguments:
        nid:
          admin_label: null
          exception:
            title: 全部
          title: null
  block_park_children:
    display_title: 公园儿童
    display_options:
      display_description: null
  block_park_siblings:
    display_title: 公园兄弟姐妹
    display_options:
      title: null
      fields:
        field_located_within:
          admin_label: null
          label: null
          alter:
            text: '<h2>{{ field_located_within }} 中的更多内容</h2>'
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
        nid:
          admin_label: null
          label: null
          alter:
            text: null
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
        title_1:
          admin_label: null
          label: null
          alter:
            path: null
            alt: null
            prefix: null
            suffix: null
            more_link_text: null
          separator: ','
      sorts:
        title:
          admin_label: null
          expose:
            label: null
      filters:
        type:
          admin_label: null
          expose:
            label: null
            description: null
          group_info:
            label: null
            description: null
      display_description: null
