title: 报告营地搬迁投诉
description: null
elements: |
  section_report:
    '#title': 报告
  report_problem_type:
    '#title': 发生了什么类型的问题？
    '#options':
      'My property was taken.': 我的部分或全部财产没有妥善存放。
      'A City employee or contractor was disrespectful.': 城市雇员或承包商不尊重人。
    '#other__option_label': 别的东西
    '#other__placeholder': 请描述。
  markup_property_collection:
    '#markup': '<div class="alert alert--info next-steps"><h2>信息</h2><p>如果您想找到您的财产，请先致电<a href="tel:+1-503-387-1336">503-387-1336 联系</a>Rapid Response Bio Clean 存储设施。您可以在周一至周五上午 9:30 至下午 3:30 或周六上午 10:30 至下午 2:30 拨打电话。<br /><br />他们将本市收集的所有财产在收集之日起至少三十 (30) 天。<strong data-renderer-mark="true">如果您的财产仍然丢失，请继续填写此表格以报告问题。</strong></p></div>'
  report_employer:
    '#title': 这个人为谁工作？
    '#options':
      'Rapid Response Bio Clean': 'Rapid Response Bio Clean（员工身穿红色衬衫，背面印有该项目的标志）—— <img src="https://www.portland.gov/sites/default/files/styles/thumbnail/public/2022/rapidresponsebio-clean.jpg" />'
      'Central City Concern Clean Start Employee': 'Central City Concern Clean Start 员工（员工身着亮橙色衬衫，正面印有该计划的标志）—— <img src="https://www.portland.gov/sites/default/files/styles/thumbnail/public/2022/clean-start-shirt.jpg" />'
      'Portland Bureau of Transportation': 波特兰交通局
      'Portland Fire & Rescue': 波特兰消防救援
      'Portland Police Bureau': 波特兰警察局
  markup_ombudsman:
    '#markup': '<div class="alert alert--info next-steps"><h2>下一步</h2><p>请向<a href="https://www.portland.gov/ombudsman/make-complaint-about-city-bureau-or-office">波特兰市监察员</a>提出投诉。</p></div>'
  markup_ipr:
    '#markup': '<div class="alert alert--info next-steps"><h2>下一步</h2><p>请向<a href="https://www.portland.gov/ipr/submit-complaint-or-commendation-about-police">独立警察审查委员会</a>提出投诉。</p></div>'
  report_date:
    '#title': 事件何时发生？
  report_location:
    '#title': 事件发生在哪里？
    '#location_type__title': 事件发生在哪里？
    '#location_address__title': 事件发生在哪里？
    '#location_park_container__title': 公园列表容器
    '#waterway_instructions__title': 航道说明
    '#location_private_owner__title': 你是物业的主人吗？
    '#location_map__title': 位置图
    '#suggestions_modal__title': 建议
    '#status_modal__title': 状态指示灯
    '#place_name__title': 地名
    '#location_details__title': 位置详情
    '#location_lat__title': 纬度
    '#location_lon__title': 经度
    '#location_asset_id__title': '资产 ID'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  report_description:
    '#title': 用你自己的话描述事件。请解释发生了什么事，涉及谁，以及任何财产被拿走和没有妥善存放。
    '#description': 为保护您的隐私，<strong>请勿</strong>包含任何个人或健康相关信息。
  report_has_witnesses:
    '#title': 事件有目击者吗？
    '#options':
      'Yes': 是的
      'No': 不
  report_known_witnesses:
    '#title': 您知道他们的姓名和电话号码或电子邮件地址吗？
    '#description': 只有在必要时才会联系证人以调查您的投诉。如果被联系，证人可以选择是否参加。
    '#options':
      'Yes': 是的
      'No': 不
  report_witness1_name:
    '#title': 第一证人姓名
  report_witness1_phone:
    '#title': 第一个见证电话
  report_witness1_email:
    '#title': 第一个见证人电子邮件
  report_witness2_name:
    '#title': 第二证人姓名
  report_witness2_phone:
    '#title': 第二证人电话
  report_witness2_email:
    '#title': 第二个见证人电子邮件
  report_photo:
    '#title': 如果合适，请附上与您的投诉相关的任何照片或其他材料。
  section_contact:
    '#title': 您的联系信息
  contact_name:
    '#title': 姓名
  contact_email:
    '#title': 电子邮件
    '#description': 我们将使用您的电子邮件确认您的提交。
  contact_phone:
    '#title': 电话
    '#description': 如果我们需要更多信息，请提供您的电话号码。
  contact_preference:
    '#title': 如果需要，您希望我们通过电话或电子邮件与您联系吗？
    '#options':
      Phone: 电话
      Email: 电子邮件
  section_public_records_statement:
    '#title': 公共记录声明
  public_records_statement_standard:
    '#markup': '您向纽约市提供的信息是公共记录，可能会根据俄勒冈州的<a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">公共记录法</a>予以公布。该法律将某些信息分类为可应要求向公众提供的信息。有关更多信息，请参阅我们的<a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">隐私声明</a>。'
  actions:
    '#title': 提交按钮
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: 投诉已提交
  confirmation_message: '感谢您向我们提供这些信息。波特兰市减少影响计划的一名员工将在 14 个工作日内与您联系。如果您想提供有关您的投诉的更多信息，请发送电子邮件至<a href="mailto:reportpdx@portlandoregon.gov">reportpdx@portlandoregon.gov</a> 。'
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  submit_report_to_reportpdx:
    label: 提交报告至reportpdx@portlandoregon.gov
    notes: null
    settings:
      from_name: null
      reply_to: null
      return_path: null
      sender_name: null
      subject: _默认
      body: '<p>在 [webform_submission:created] 上提交</p><p>提交的值是：</p> [webform_submission：值]'
