title: 报告公共垃圾桶的问题
description: null
elements: |
  section_report:
    '#title': 报告
  report_location:
    '#title': 公共垃圾桶的位置
    '#location_address__title': 地址
    '#location_address__description': '输入地址，然后按定位按钮在地图上找到它，或使用 +/- 缩放控件放大并找到您要报告的垃圾桶。'
    '#location_map__title': 地图上的位置标记
    '#location_map__description': '<em>公共垃圾桶用灰色标记显示<img src="/modules/custom/portland/modules/portland_location_picker/images/map_marker_trashcan.png" alt="垃圾箱地图标记图标" class="inline-icon">当地图完全放大时。单击垃圾桶将其选中。已报告的垃圾桶用红色标记显示<img src="/modules/custom/portland/modules/portland_location_picker/images/map_marker_incident.png" alt="红色地图标记图标" class="inline-icon"> .</em>'
    '#place_name__title': 精选垃圾桶
    '#place_name__description': 通过在地图上单击来选择一个垃圾桶。
    '#location_asset_id__title': 精选垃圾桶
    '#selected_asset_name__title': 选定资产
    '#location_type__title': 问题位于哪种类型的财产上？
    '#location_park_container__title': 公园列表容器
    '#waterway_instructions__title': 航道说明
    '#location_private_owner__title': 你是物业的主人吗？
    '#suggestions_modal__title': 建议
    '#status_modal__title': 状态指示灯
    '#location_details__title': 位置详情
    '#location_lat__title': 纬度
    '#location_lon__title': 经度
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  report_issue:
    '#title': 垃圾桶有什么问题？
    '#options':
      Overflowing: 溢出
      'Broken lock': 锁坏了
      Damaged: 损坏的
      Graffiti: 涂鸦
      'Door is open': 门是开着的
  section_contact:
    '#title': 您的联系信息
  contact_name:
    '#title': 姓名
  contact_email:
    '#title': 电子邮件
    '#description': 我们将使用您的电子邮件回复您的反馈或请求。
  section_public_records_statement:
    '#title': 公共记录声明
  public_records_statement_required:
    '#markup': '根据俄勒冈州<a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly">公共记录法</a>，您在本表格中提供的信息被视为公共记录，可应要求提供给公众。'
  section_agent_use_only:
    '#title': 仅限代理使用
  agent_email:
    '#title': 代理电子邮件
    '#default_value': '[当前用户：显示名称] <[当前用户：邮件]>'
  agent_ticket_number:
    '#title': 票号
  agent_action_taken:
    '#title': 采取的行动
  agent_contact_type:
    '#title': 联系方式
  agent_ticket_type:
    '#title': 票种
  agent_summary:
    '#title': 代理摘要
  report_ticket_id:
    '#title': '支持工单 ID'
  actions:
    '#title': 提交按钮
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_new_ticket:
    label: 'Zendesk 新票'
    notes: null
