label: 'Manage: Group: Members'
display:
  default:
    display_options:
      fields:
        name:
          label: អ្នក​ប្រើ
        group_roles:
          label: តួនាទី​
        changed:
          label: បាន​ធ្វើ​បច្ចុប្បន្នភាព
        edit_group_content:
          text: 'Edit membership'
        delete_group_content:
          text: Remove
      exposed_form:
        options:
          reset_button_label: កំណត់​ឡើង​វិញ
      arguments:
        gid:
          exception:
            title: ទាំងអស់
          title: 'Manage {{ arguments.gid|placeholder }} members'
  page_1:
    display_title: ទំព័រ
