label: ឯកសារ
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: តម្រង
          reset_button_label: កំណត់​ឡើង​វិញ
      fields:
        filename:
          label: ឈ្មោះ
        filemime:
          label: 'ប្រភេទ​ MIME'
        filesize:
          label: ទំហំ
        status:
          label: ស្ថានភាព
        count:
          label: បាន​ប្រើ​ក្នុង
      filters:
        filename:
          expose:
            label: ឈ្មោះ​ឯកសារ
        filemime:
          expose:
            label: 'ប្រភេទ​ MIME'
        status:
          expose:
            label: ស្ថានភាព
      title: ឯកសារ
  page_1:
    display_options:
      menu:
        title: ឯកសារ
  page_2:
    display_options:
      arguments:
        fid:
          exception:
            title: ទាំងអស់
