label: មនុស្ស
description: "រក​ និង​គ្រប់​គ្រង​មនុស្ស​ដែល​មាន​ទំនាក់​ទំនង​ជាមួយ​តំបន់​បណ្តាញ​របស់​អ្នក​\_។"
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: តម្រង
          reset_button_label: កំណត់​ឡើង​វិញ
      fields:
        name:
          label: ឈ្មោះអ្នក​ប្រើ
        status:
          label: ស្ថានភាព
          settings:
            format_custom_true: សកម្ម
            format_custom_false: បាន​ទប់ស្កាត់
        roles_target_id:
          label: តួនាទី​
        created:
          label: សមាជិក​សម្រាប់
        access:
          label: ចូលដំណើរការ​ចុងក្រោយ
        operations:
          label: ប្រតិបត្តិការ
      filters:
        status:
          group_info:
            label: ស្ថានភាព
            group_items:
              1:
                title: សកម្ម
              2:
                title: បាន​ទប់ស្កាត់
        roles_target_id:
          expose:
            label: តួនាទី
        permission:
          expose:
            label: សិទ្ធិ
      title: មនុស្ស
      empty:
        area_text_custom:
          content: 'គ្មាន​មនុស្ស​ទេ ។'
      use_more_text: បន្ថែមទៀត
  page_1:
    display_title: ទំព័រ
    display_options:
      menu:
        title: បញ្ជី
        description: "រក​ និង​គ្រប់​គ្រង​មនុស្ស​ដែល​មាន​ទំនាក់​ទំនង​ជាមួយ​តំបន់​បណ្តាញ​របស់​អ្នក​\_។"
      tab_options:
        title: មនុស្ស
        description: 'គ្រប់គ្រង​គណនី​អ្នកប្រើ តួនាទី និង​សិទ្ធិ ។'
