login_path: /user/login
_core:
  default_config_hash: ZKVq7lpyGFQf-SCuj_Ng2yLPD24rKHxz-TzGQxBjLl4
paths: "~/openid-connect/azure\r\n~/sites/default/files/**\r\n/admin\r\n/admin/*\r\n/my-groups\r\n/my-content\r\n/my-media\r\n/group/*/edit\r\n/group/*/members\r\n/group/*/nodes\r\n/group/*/media\r\n/group/*/node/create\r\n/group/*/media/create\r\n~/node/*/news\r\n~/node/*/events\r\n~/node/*/events/past\r\n/node/*/*\r\n/user"
message: 'Welcome to the beta version of the new website platform for Portland, Oregon. City employees with a ROSE or PTLD account may log in, only assigned group admins and editors can edit content.'
