form_ids:
  - comment_comment_form
  - user_login_form
  - user_pass
  - user_register_form
  - contact_message_feedback_form
  - contact_message_personal_form
  - webform_submission_website_feedback_add_form
show_form_ids: 1
_core:
  default_config_hash: f8-7hVX66ftHnUweoB4XDVx8q1hEr4PiqFvPvFB6yRc
