form_ids:
  - 'comment_*'
  - user_login_form
  - user_pass
  - user_register_form
  - 'contact_*'
  - website_feedback
show_form_ids: false
_core:
  default_config_hash: 7QwhifH5gAzkdFMMDFV6XQRrcx4PAvtROZO8rs19nTo
