allowed_roles:
  authenticated: authenticated
  publisher: publisher
  policy_author: policy_author
  policy_editor: policy_editor
  attorney: attorney
  council_author: council_author
  council_clerk: council_clerk
  budget: budget
  park_editor: park_editor
  code_editor: code_editor
  group_creator: group_creator
  alert_editor: alert_editor
  sitewide_editor: sitewide_editor
  administrator: '0'
_core:
  default_config_hash: QqhYOhPHWGDL9oSnXSdIaYuEA3hHLDNjYouaWatEXc8
