minimum_single: 0
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 0
jquery_selector: 'select#edit-field-topics, select#edit-field-audience, select#edit-field-community-actions'
search_contains: true
disable_search: false
allow_single_deselect: true
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  seven: '0'
  adminimal_theme: '0'
  bootstrap_barrio: '0'
  cloudy: '0'
  tweme: '0'
chosen_include: 2
_core:
  default_config_hash: JUHKHJeHl1bWXY41HMIcDR-VmAWvJ4OJycDubCkIeDU
