verbose: 1
types:
  block_content: {  }
  consumer: {  }
  contact_message: {  }
  content_moderation_state: {  }
  crop: {  }
  file: {  }
  group:
    '*': '*'
  group_content: {  }
  media: {  }
  node:
    '*': '*'
  redirect: {  }
  search_api_task: {  }
  shortcut: {  }
  oauth2_token: {  }
  taxonomy_term: {  }
  user: {  }
  webform_submission: {  }
  menu_link_content: {  }
  paragraph: {  }
  entity_embed_fake_entity: {  }
  feeds_subscription: {  }
  feeds_feed: {  }
  path_alias: {  }
  relation: {  }
types_translation_lock: {  }
types_js_lock:
  1: media
  2: node
form_op_lock:
  block_content:
    mode: 0
    values: {  }
  consumer:
    mode: 0
    values: {  }
  contact_message:
    mode: 0
    values: {  }
  content_moderation_state:
    mode: 0
    values: {  }
  crop:
    mode: 0
    values: {  }
  file:
    mode: 0
    values: {  }
  group:
    mode: 1
    values:
      edit: edit
  group_content:
    mode: 0
    values: {  }
  media:
    mode: 0
    values: {  }
  node:
    mode: 1
    values:
      edit: edit
  redirect:
    mode: 0
    values: {  }
  search_api_task:
    mode: 0
    values: {  }
  shortcut:
    mode: 0
    values: {  }
  oauth2_token:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  webform_submission:
    mode: 0
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
  paragraph:
    mode: 0
    values: {  }
  entity_embed_fake_entity:
    mode: 0
    values: {  }
  feeds_subscription:
    mode: 0
    values: {  }
  feeds_feed:
    mode: 0
    values: {  }
  path_alias:
    mode: 0
    values: {  }
  relation:
    mode: 0
    values: {  }
_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
