definitions:
  portland__my-profile:
    weight: -45
    menu_name: editor-toolbar
    parent: ''
    expanded: false
    enabled: false
  portland__logout:
    weight: -36
    menu_name: editor-toolbar
    parent: ''
    expanded: false
    enabled: false
  metatag__reports_plugins:
    weight: 1
    menu_name: admin
    parent: system.admin_reports
    enabled: true
    expanded: false
  field_permissions__reports:
    weight: 2
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  system__status:
    weight: 3
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  dblog__access_denied:
    weight: 4
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  dblog__page_not_found:
    weight: 5
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  views_ui__reports_plugins:
    weight: 7
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  webform__reports_plugins:
    weight: 8
    menu_name: admin
    parent: system.admin_reports
    expanded: false
    enabled: true
  redirect_404__fix_404:
    weight: 1
    menu_name: admin
    parent: redirect.list
    enabled: true
    expanded: false
  redirect__settings:
    weight: 3
    menu_name: admin
    parent: redirect.list
    enabled: true
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
