module:
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  anonymous_login: 0
  antibot: 0
  automated_cron: 0
  block: 0
  block_content: 0
  block_exclude_pages: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  ckeditor: 0
  ckeditor_config: 0
  cleave: 0
  color: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_split: 0
  content_lock: 0
  content_lock_timeout: 0
  content_moderation: 0
  contextual: 0
  copyright_block: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  custom_add_another: 0
  datalayer: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  draggableviews: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_browser_table: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  entity_usage: 0
  environment_indicator: 0
  eva: 0
  facets: 0
  feeds: 0
  feeds_ex: 0
  field: 0
  field_defaults: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  file_replace: 0
  filter: 0
  fixed_block_content: 0
  focal_point: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  gnode: 0
  google_tag: 0
  group: 0
  groupmedia: 0
  hal: 0
  help: 0
  honeypot: 0
  ief_table_view_mode: 0
  image: 0
  image_effects: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  key: 0
  language: 0
  layout_builder: 0
  layout_builder_st: 0
  layout_discovery: 0
  leaflet: 0
  leaflet_views: 0
  lightning_core: 0
  lightning_media: 0
  lightning_media_document: 0
  lightning_media_image: 0
  lightning_media_video: 0
  lightning_scheduler: 0
  lightning_workflow: 0
  link: 0
  link_class: 0
  linkit: 0
  mailsystem: 0
  masquerade: 0
  maxlength: 0
  media: 0
  media_embed_arcgis_online: 0
  media_embed_field: 0
  media_embed_google_maps: 0
  media_embed_media: 0
  media_embed_portland_maps: 0
  media_embed_portland_maps_charts: 0
  media_embed_portlandoregon: 0
  media_embed_tableau: 0
  media_library: 0
  menu_breadcrumb: 0
  menu_link: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  mimemail: 0
  moderation_dashboard: 0
  monolog: 0
  node: 0
  openid_connect: 0
  openid_connect_windows_aad: 0
  options: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  path: 0
  path_alias: 0
  path_alias_xt: 0
  portland: 0
  portland_address_complete: 0
  portland_content_completion: 0
  portland_edit_forms: 0
  portland_file_replace: 0
  portland_groups: 0
  portland_leaflet_maps: 0
  portland_legacy_redirects: 0
  portland_media_embed_helper: 0
  portland_migrations: 0
  portland_openid_connect: 0
  portland_quick_entry: 0
  portland_relations: 0
  portland_revision_helper: 0
  quick_node_clone: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  remove_http_headers: 0
  responsive_image: 0
  rest: 0
  rh_group: 0
  rh_node: 0
  rules: 0
  schemata: 0
  schemata_json_schema: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  search_api_location: 0
  search_api_page: 0
  search_api_solr: 0
  seckit: 0
  sendgrid_integration: 0
  serialization: 0
  shortcut: 0
  sophron: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  telephone: 0
  telephone_validation: 0
  text: 0
  textarea_widget_for_text: 0
  time_field: 0
  toc_js: 0
  toc_js_per_node: 0
  token: 0
  toolbar: 0
  toolbar_menu: 0
  transliterate_filenames: 0
  twig_tweak: 0
  typed_data: 0
  unified_twig_ext: 0
  user: 0
  variationcache: 0
  video_embed_field: 0
  video_embed_media: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_geojson: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  ds: 1
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  paragraphs: 11
  lightning: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  cloudy: 0
  claro: 0
profile: lightning
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
