fields:
  block_content:
    langcode:
      type: hidden
      settings: {  }
    revision_created:
      type: hidden
      settings: {  }
    revision_user:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    info:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    scheduled_transition_date:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    scheduled_transition_state:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    body:
      type: text_field_diff_builder
      settings:
        compare_format: 0
        show_header: 1
        markdown: drupal_html_to_text
  content_moderation_state:
    langcode:
      type: hidden
      settings: {  }
    uid:
      type: hidden
      settings: {  }
    workflow:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    moderation_state:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    content_entity_type_id:
      type: hidden
      settings: {  }
    content_entity_id:
      type: hidden
      settings: {  }
    content_entity_revision_id:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
  crop:
    langcode:
      type: hidden
      settings: {  }
    entity_id:
      type: hidden
      settings: {  }
    entity_type:
      type: hidden
      settings: {  }
    uri:
      type: hidden
      settings: {  }
    height:
      type: hidden
      settings: {  }
    width:
      type: hidden
      settings: {  }
    x:
      type: hidden
      settings: {  }
    'y':
      type: hidden
      settings: {  }
    revision_timestamp:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    scheduled_transition_date:
      type: hidden
      settings: {  }
    scheduled_transition_state:
      type: hidden
      settings: {  }
  media:
    langcode:
      type: hidden
      settings: {  }
    revision_created:
      type: hidden
      settings: {  }
    revision_user:
      type: hidden
      settings: {  }
    revision_log_message:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    name:
      type: hidden
      settings: {  }
    thumbnail:
      type: hidden
      settings: {  }
    uid:
      type: hidden
      settings: {  }
    created:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    scheduled_transition_date:
      type: hidden
      settings: {  }
    scheduled_transition_state:
      type: hidden
      settings: {  }
    field_document:
      type: hidden
      settings: {  }
    field_media_in_library:
      type: hidden
      settings: {  }
    field_media_video_embed_field:
      type: hidden
      settings: {  }
    field_summary:
      type: hidden
      settings: {  }
    field_transcript:
      type: hidden
      settings: {  }
    image:
      type: hidden
      settings: {  }
  node:
    langcode:
      type: hidden
      settings: {  }
    revision_timestamp:
      type: hidden
      settings: {  }
    status:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    title:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    uid:
      type: hidden
      settings: {  }
    created:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    promote:
      type: hidden
      settings: {  }
    sticky:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    scheduled_transition_date:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    scheduled_transition_state:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    body:
      type: text_summary_field_diff_builder
      settings:
        compare_format: 0
        compare_summary: 0
        show_header: 1
        markdown: drupal_html_to_text
    field_action_link:
      type: link_field_diff_builder
      settings:
        compare_title: 0
        compare_uri: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_active_time_frame:
      type: hidden
      settings: {  }
    field_address:
      type: hidden
      settings: {  }
    field_all_day:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_audience:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_body:
      type: entity_reference_revisions_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_building:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_community_actions:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_end_date:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_end_time:
      type: hidden
      settings: {  }
    field_event_location:
      type: entity_reference_revisions_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_floor:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_get_directions:
      type: link_field_diff_builder
      settings:
        compare_title: 0
        compare_uri: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_legacy_path:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_notification_severity:
      type: list_field_diff_builder
      settings:
        compare: key
        show_header: 1
        markdown: drupal_html_to_text
    field_open_hours:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_related_content:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_revision_log_message:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_search_link:
      type: link_field_diff_builder
      settings:
        compare_title: 0
        compare_uri: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_service_mode:
      type: entity_reference_revisions_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_severity:
      type: list_field_diff_builder
      settings:
        compare: key
        show_header: 1
        markdown: drupal_html_to_text
    field_start_date:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_start_time:
      type: hidden
      settings: {  }
    field_summary:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_time_to_complete:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_topics:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
  paragraph:
    langcode:
      type: hidden
      settings: {  }
    uid:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    created:
      type: hidden
      settings: {  }
    behavior_settings:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    default_langcode:
      type: hidden
      settings: {  }
    revision_default:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    scheduled_transition_date:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    scheduled_transition_state:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_address:
      type: hidden
      settings: {  }
    field_alignment:
      type: list_field_diff_builder
      settings:
        compare: key
        show_header: 1
        markdown: drupal_html_to_text
    field_attribution:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_building:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_caption:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_cards:
      type: entity_reference_revisions_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_card_title:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_citation:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_column:
      type: entity_reference_revisions_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_document:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_email_link:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_email_text:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_fax_number:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_form_button:
      type: link_field_diff_builder
      settings:
        compare_title: 0
        compare_uri: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_image:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_image_alignment:
      type: list_field_diff_builder
      settings:
        compare: key
        show_header: 1
        markdown: drupal_html_to_text
    field_link_style:
      type: list_field_diff_builder
      settings:
        compare: key
        show_header: 1
        markdown: drupal_html_to_text
    field_location_name:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_location_type:
      type: entity_reference_revisions_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_phone_number:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_quoted_text:
      type: text_field_diff_builder
      settings:
        compare_format: 0
        show_header: 1
        markdown: drupal_html_to_text
    field_select_a_group:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_service_location:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_service_modes:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_step_action_button:
      type: entity_reference_revisions_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_step_by_step_instructions:
      type: entity_reference_revisions_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_step_instruction:
      type: text_field_diff_builder
      settings:
        compare_format: 0
        show_header: 1
        markdown: drupal_html_to_text
    field_step_title:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_text:
      type: text_field_diff_builder
      settings:
        compare_format: 0
        show_header: 1
        markdown: drupal_html_to_text
    field_video:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_video_alignment:
      type: list_field_diff_builder
      settings:
        compare: key
        show_header: 1
        markdown: drupal_html_to_text
