general_settings:
  radio_behavior: simple
  context_lines_leading: 1
  context_lines_trailing: 1
  revision_pager_limit: 50
  layout_plugins:
    split_fields:
      enabled: true
      weight: -50
    visual_inline:
      enabled: true
      weight: -49
    unified_fields:
      enabled: true
      weight: -48
  visual_inline_theme: default
_core:
  default_config_hash: oXwX3NzLv9QK_LbNEvpQ9OPwH9tqtMSJzq5y8t63Q8w
