include_home_segment: false
home_segment_title: Home
home_segment_keep: false
include_title_segment: false
language_path_prefix_as_segment: false
use_menu_title_as_fallback: true
remove_repeated_segments: true
absolute_paths: false
hide_single_home_item: true
_core:
  default_config_hash: ALaJtTMWaPkrzRKrWM1z4u7BslSR_0tTzlGXfeZPhDQ
include_invalid_paths: false
excluded_paths: ''
replaced_titles: ''
segments_separator: null
title_segment_as_link: false
title_from_page_when_available: true
term_hierarchy: true
applies_admin_routes: true
custom_paths: ''
use_page_title_as_menu_title_fallback: true
