_core:
  default_config_hash: '-7-Rw6N-YenqEkgEjRhGUAX4GsoyqXN8luAfZihueG4'
content_root: ''
assertiveness: smart
no_load: ''
ignore_all_if_absent: '.contextual-region a[href*="/edit"], .contextual-region a[href*="/manage"]'
ignore_elements: '#block-portlandcontentcompetionblock *, #block-portlandlegacypathsblock *, .field--name-field-destination-url *, .leaflet-container *, .get-directions-link *, .view-eva.view-locations *, .media--type-iframe-embed *'
embedded_content_warning: .media--type-iframe-embed
download_links: "div.field--name-field-document a[href$='/download']"
link_strings_new_windows: ''
ignore_link_strings: ''
link_ignore_selector: 'svg.ext, svg.mailto, .link-purpose-text, .extlink'
hidden_handlers: ''
ed11y_theme: sleekTheme
shadow_components: ''
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
redundant_prefix: ''
custom_tests: 0
