unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: link
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_personal_form: false
  contact_message_sitewide_form: false
  node_alert_form: false
  node_building_form: false
  node_charter_article_form: false
  node_charter_chapter_form: false
  node_charter_section_form: false
  node_city_service_form: false
  node_code_chapter_form: false
  node_code_section_form: false
  node_code_title_form: false
  node_council_document_form: false
  node_council_meeting_form: false
  node_development_permit_form: false
  node_event_form: false
  node_external_resource_form: false
  node_location_form: false
  node_news_form: false
  node_notification_form: false
  node_page_form: false
  node_park_facility_form: false
  node_policy_form: false
  node_service_location_form: false
  node_top_search_form: false
_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
