quality: 75
binaries: imagemagick
path_to_binaries: ''
prepend: ''
log_warnings: true
debug: false
locale: en_US.UTF-8
advanced:
  density: 0
  colorspace: '0'
  profile: ''
  coalesce: false
image_formats:
  PNG:
    mime_type: image/png
  JPEG:
    mime_type: image/jpeg
  JPG:
    mime_type: image/jpeg
    weight: 10
    enabled: false
  GIF:
    mime_type: image/gif
  GIF87:
    mime_type: image/gif
    weight: 10
    enabled: false
  SVG:
    mime_type: image/svg+xml
    enabled: false
  WEBP:
    mime_type: image/webp
    enabled: false
_core:
  default_config_hash: cp-t_XKrU3l5dl9BIOiM-favydmIDTQhL11eF-1MjRc
