always_save_userinfo: true
connect_existing_users: true
override_registration_settings: true
userinfo_mappings:
  timezone: '0'
  metatag: 0
  path: 0
  user_picture: 0
_core:
  default_config_hash: kli1Xws0l--Y-jy-9ZTGApFO_EFk9DMawoetjMk76Ro
