enabled: false
settings:
  client_id: null
  client_secret: null
  authorization_endpoint: 'https://login.microsoftonline.com/common/oauth2/authorize'
  token_endpoint: 'https://login.microsoftonline.com/common/oauth2/token'
  userinfo_endpoint: 'https://graph.windows.net/me?api-version=1.6'
_core:
  default_config_hash: b5Nmh4U49pSzYWhpp-sT_EopsYtYKQ_Jf9xEuvw9ddE
