_core:
  default_config_hash: 6XRelHPjACQVOo9yRQMmbXt-ysCA2Pt6l762bxQQbdw
exclude:
  node:
    council_document:
      - field_amended_by_council
      - field_auditor
      - field_council_clerk
      - field_council_document_status
      - field_date_of_final_disposition
      - field_substituted_by_council
  paragraph: {  }
text_to_prepend_to_title: ''
clone_status: false
