apikey: sendgrid_api
test_defaults:
  to: xinju.wang@portlandoregon.gov
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: ''
  to_name: ''
  reply_to: ''
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
