stormy_sidebar_position: both
stormy_content_offset: 0
stormy_sidebar_first_width: 4
stormy_sidebar_first_offset: 0
stormy_sidebar_second_width: 3
stormy_sidebar_second_offset: 0
stormy_fluid_container: 0
stormy_button_size: ''
stormy_button_outline: 0
stormy_navbar_toggle: 1
stormy_navbar_container: navbar-toggleable-md
stormy_navbar_top_position: ''
stormy_navbar_top_color: navbar-dark
stormy_navbar_top_background: bg-dark
stormy_navbar_position: ''
stormy_navbar_color: navbar-dark
stormy_navbar_background: bg-primary
_core:
  default_config_hash: '-9Rhh9hsC5k-QlprPyg7v5lFjneYY0p2jXcc_n8lowA'
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: profiles/contrib/lightning/lightning.png
favicon:
  use_default: false
  path: profiles/contrib/lightning/favicon.ico
  mimetype: image/vnd.microsoft.icon
bootstrap_barrio_library: cdn
bootstrap_barrio_fluid_container: 0
bootstrap_barrio_sidebar_position: left
bootstrap_barrio_content_offset: '0'
bootstrap_barrio_sidebar_collapse: 0
bootstrap_barrio_sidebar_first_width: '2'
bootstrap_barrio_sidebar_first_offset: '0'
bootstrap_barrio_sidebar_second_width: '2'
bootstrap_barrio_sidebar_second_offset: '0'
bootstrap_barrio_button_outline: 0
bootstrap_barrio_button_size: ''
bootstrap_barrio_navbar_container: 0
bootstrap_barrio_navbar_toggle: navbar-toggleable-lg
bootstrap_barrio_navbar_top_navbar: 1
bootstrap_barrio_navbar_top_position: ''
bootstrap_barrio_navbar_top_color: navbar-dark
bootstrap_barrio_navbar_top_background: bg-dark
bootstrap_barrio_navbar_position: ''
bootstrap_barrio_navbar_color: navbar-dark
bootstrap_barrio_navbar_background: bg-dark
bootstrap_barrio_navbar_top_affix: 0
bootstrap_barrio_navbar_affix: 0
bootstrap_barrio_sidebar_first_affix: 0
bootstrap_barrio_sidebar_second_affix: 0
bootstrap_barrio_scroll_spy: ''
bootstrap_barrio_google_fonts: monserrat_lato
bootstrap_barrio_icons: material_design_icons
bootstrap_barrio_system_messages: messages_dark
