spt_table:
  -
    pages: "/my-content\r\n/my-media\r\n/my-groups\r\n/group/*/edit\r\n/group/*/delete\r\n/group/*/manage-display\r\n/group/*/content\r\n/group/*/members\r\n/group/*/nodes\r\n/group/*/media"
    theme: adminimal_theme
    weight: '-10'
    status: 0
    roles:
      anonymous: 0
      authenticated: 0
      administrator: 0
      sitewide_editor: 0
    remove: Remove
