_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: 191eddb9-0929-4dbd-bbfa-3f97bf1d93e0
name: Portland.gov
mail: website@portlandoregon.gov
slogan: 'The official website of the City of Portland, Oregon.'
page:
  403: ''
  404: /system/404
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
