display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
          tags:
            previous: ‹‹
            next: ››
      fields:
        media_bulk_form:
          action_title: 액션
      filters:
        status:
          group_info:
            label: 공개
        name:
          expose:
            label: 이름
        langcode:
          expose:
            label: 언어
      sorts:
        created:
          expose:
            label: '새로운 것부터'
      title: 미디어
  page:
    display_title: 쪽
    display_options:
      fields:
        media_bulk_form:
          action_title: 액션
        edit_media:
          text: 편집하기
        delete_media:
          text: 삭제하기
  widget:
    display_title: 위젯
    display_options:
      arguments:
        bundle:
          exception:
            title: 전체
      header:
        display_link_grid:
          label: 그리드
        display_link_table:
          label: 표
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: 썸네일
        name:
          label: 이름
        uid:
          label: 작성자
        changed:
          label: 갱신됨
      arguments:
        bundle:
          exception:
            title: 전체
      header:
        display_link_grid:
          label: 그리드
        display_link_table:
          label: 표
