label: 미디어
display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          submit_button: 필터
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
          tags:
            previous: '‹ 이전'
            next: '다음 ›'
            first: '« 처음'
            last: '마지막 »'
      fields:
        thumbnail__target_id:
          label: 썸네일
        bundle:
          label: 종류
        uid:
          label: 작성자
        status:
          label: 상태
          settings:
            format_custom_true: 공개
            format_custom_false: 비공개
        changed:
          label: 갱신됨
        operations:
          label: 작업
      filters:
        bundle:
          expose:
            label: 종류
        status:
          expose:
            label: 참
          group_info:
            label: '공개 상태'
            group_items:
              1:
                title: 공개
              2:
                title: 비공개
        langcode:
          expose:
            label: 언어
      title: 미디어
  media_page_list:
    display_title: 미디어
