label: 파일
display:
  default:
    display_title: 기본값
    display_options:
      title: 파일
      fields:
        filename:
          label: 이름
        filemime:
          label: 'MIME 유형'
        filesize:
          label: '파일 크기'
        status:
          label: 상태
          settings:
            format_custom_false: 임시
            format_custom_true: 영구
        created:
          label: '올린 날짜'
        changed:
          label: '변경 날짜'
        count:
          label: '사용 위치'
      pager:
        options:
          tags:
            next: '다음 ›'
            previous: '‹ 이전'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      exposed_form:
        options:
          submit_button: 필터
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      empty:
        area_text_custom:
          content: '사용할 수 있는 파일이 없습니다.'
      filters:
        filename:
          expose:
            label: 파일명
        filemime:
          expose:
            label: 'MIME 유형'
        status:
          expose:
            label: 상태
  page_1:
    display_options:
      menu:
        title: 파일
  page_2:
    display_title: '파일 사용량'
    display_options:
      title: '파일 사용량'
      fields:
        entity_label:
          label: 엔터티
        type:
          label: '엔터티 유형'
        module:
          label: '등록 모듈'
        count:
          label: '사용 횟수'
      pager:
        options:
          tags:
            next: '다음 ›'
            previous: '‹ 이전'
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
      arguments:
        fid:
          exception:
            title: 전체
