label: '시스템 감시'
description: '최근 로그 메시지'
display:
  default:
    display_title: 마스터
    display_options:
      exposed_form:
        options:
          submit_button: 필터
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      pager:
        options:
          expose:
            items_per_page_label: '페이지 당 항목 수'
            items_per_page_options_all_label: '- 모두 -'
            offset_label: 건너뛰기
          tags:
            previous: ‹‹
            next: ››
      fields:
        nothing:
          admin_label: 아이콘
        wid:
          label: WID
        severity:
          label: 심각성
        type:
          label: 종류
        timestamp:
          label: 날짜
        message:
          label: 메시지
        name:
          label: 사용자
        link:
          label: 작업
      filters:
        type:
          expose:
            label: 종류
        severity:
          expose:
            label: 심각성
      title: '최근 로그 메시지'
      empty:
        area:
          admin_label: '로그 메시지가 없습니다.'
          content: '로그 메시지가 없습니다.'
  page:
    display_title: 쪽
