label: '최근 콘텐츠'
display:
  default:
    display_title: 기본값
    display_options:
      title: '최근 콘텐츠'
      exposed_form:
        options:
          submit_button: 적용
          reset_button_label: 재설정
          exposed_sorts_label: 정렬기준
          sort_asc_label: Asc
          sort_desc_label: 설명
      empty:
        area_text_custom:
          content: '콘텐츠가 없습니다.'
      use_more_text: '더 보기'
  block_1:
    display_title: 블록
