settings:
  default_submit_button_label: 전송
  default_reset_button_label: 재설정
  default_wizard_start_label: 시작
  default_wizard_confirmation_label: 완료
  default_preview_next_button_label: 미리보기
  default_preview_label: 미리보기
  dialog_options:
    normal:
      title: 보통
element:
  default_more_title: '더 보기'
