name: 'Filtrar por a침o completo'
url_alias: a침o_de_finalizaci칩n
widget:
  config:
    reset_text: 'Mostrar todo'
    soft_limit_settings:
      show_less_label: 'Muestra menos'
      show_more_label: 'Mostrar m치s'
