third_party_settings:
  toc_js:
    title: 'En esta página'
    back_to_top_label: 'Volver arriba'
name: 'instalación del parque'
description: 'Un parque o instalación de parque está asociado con una dirección (para entrada o estacionamiento) y también puede tener información geográfica para describir el espacio que ocupa. Tres taxonomías ayudan a definir un parque: tipo de instalación del parque, servicios del parque, reservas disponibles.'
help: null
