name: Notificación
description: 'Las notificaciones ayudan a informar a la comunidad sobre información importante que una oficina u oficina desea resaltar durante un período de tiempo limitado. Son despedibles por un miembro de la comunidad.'
help: null
