third_party_settings:
  toc_js:
    title: 'Tabla de contenido'
    back_to_top_label: 'Volver arriba'
name: Recurso
description: 'Un recurso es contenido o una aplicación que no está alojada en Portland.gov o que no se puede indexar en Portland.gov, como una vista de búsqueda. Los recursos se pueden usar para los servicios estatales, del condado y del área metropolitana para crear un resultado de búsqueda con un resumen. Los recursos también se pueden usar para crear un enlace que se puede destacar y apunta a una búsqueda. (por ejemplo, Find a Park es un recurso porque la página en /parks/search no está disponible para nuestro índice de búsqueda ni para aparecer).'
help: null
