label: 'Término de taxonomía'
description: 'Contenido perteneciente a un determinado término de taxonomía.'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
  feed_1:
    display_title: 'Canal de noticias'
  page_1:
    display_title: Página
