title: 'Reportar Discriminación'
description: null
elements: |
  confidentiality_waiver:
    '#title': 'Exención de confidencialidad'
    '#description': 'Es política de la ciudad mantener confidencial la información que proporcione en este formulario con el fin de cumplir con su solicitud. La ciudad también intentará mantener la confidencialidad de su información en caso de que alguien solicite que se divulgue como registro público en virtud de la <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Bajo%20la%20ley%20de%20registros%20públicos%20deOregón,comité%20de%20la%20asamblea%20legislativa%20">Ley de Registros Públicos</a> de Oregón. Si prefiere renunciar a esta confidencialidad, seleccione esa opción a continuación.'
    '#options':
      'I do not waive confidentiality.': '<em>No</em> renuncio a la confidencialidad.'
      'I choose to waive confidentiality.': 'Elijo renunciar a la confidencialidad.'
  report_discrimination:
    '#title': '¿Le gustaría presentar una queja sobre una política de la Ciudad o una acción tomada por un programa, empleado o contratista de la Ciudad que viole sus derechos y lo discrimine?'
    '#options':
      'Yes': 'Sí, me gustaría denunciar discriminación'
      'No': 'No, pero me gustaría solicitar una adaptación de la ADA'
  request_ada_accommodation_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Próximos pasos</h2><p> Realice una solicitud a través del servicio de <a href="/311/ada-request">alojamiento ADA</a> de la ciudad. También puede llamarnos al <a href="tel:+1-503-823-4000">503-823-4000</a> o TTY a través del Servicio de retransmisión de Oregon: <a href="tel:711">711</a> . El personal está disponible para ayudar de lunes a viernes de 8 am a 5 pm</p></div>'
  report_how_to_complete:
    '#title': '¿Cómo le gustaría completar su solicitud o informe?'
    '#options':
      'Call us': Llámanos
      'We contact you': 'podemos contactarte'
      'Continue online': 'Continuar en línea'
  markup_contact_us_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Próximos pasos</h2><p> Llámenos al 311, <a href="tel:+15038234000">(503) 823-4000</a> o al <a href="tel:711">711</a> para TTY a través del Servicio de retransmisión de Oregon. El personal está disponible de lunes a viernes de 8:00 am a 5:00 pm, excepto días festivos federales.</p></div>'
  report_discrimination_basis:
    '#title': 'Creo que la discriminación que experimenté se basó en...'
    '#description': '(Marque todo lo que corresponda)'
  report_discrimination_date:
    '#title': '¿Cuándo ocurrió la discriminación?'
  report_discrimination_location:
    '#title': '¿Dónde ocurrió la discriminación?'
    '#location_type__title': '¿En qué tipo de propiedad se encuentra el problema?'
    '#location_park_container__title': 'Contenedor de lista de parques'
    '#waterway_instructions__title': 'Instrucciones de navegación'
    '#location_private_owner__title': '¿Es usted el dueño de la propiedad?'
    '#location_address__title': 'Dirección o cruce de calles'
    '#location_map__title': 'Mapa de localización'
    '#suggestions_modal__title': Sugerencias
    '#status_modal__title': 'Indicador de estado'
    '#place_name__title': 'Ponga su nombre'
    '#location_details__title': 'Detalles de ubicación'
    '#location_lat__title': Latitud
    '#location_lon__title': Longitud
    '#location_asset_id__title': 'ID de activo'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  report_discrimination_bureau_office_etc:
    '#title': 'Proporcione el nombre de la oficina, oficina, empleado, evento o programa de la ciudad asociado con la discriminación.'
  report_discrimination_description:
    '#title': 'En sus propias palabras, describa la supuesta discriminación.'
    '#description': 'Por favor explique lo que sucedió; quien estaba involucrado; qué política, programa o actividad fue discriminatoria (si corresponde); por qué cree que sucedió y cómo fue discriminado. Para proteger su privacidad, no incluya ninguna información personal o relacionada con la salud.'
  report_discrimination_witnesses:
    '#title': '¿Hubo testigos de la discriminación?'
  report_discrimination_witnesses_contact_known:
    '#title': '¿Sabe su nombre y número de teléfono o dirección de correo electrónico?'
    '#description': 'Solo se contactará a los testigos si es necesario para investigar su reclamo. Si se les contacta, los testigos pueden elegir si quieren participar en el proceso de investigación.'
  report_discrimination_witness_1_name:
    '#title': 'Nombre del primer testigo'
  report_discrimination_witness_1_phone:
    '#title': 'Teléfono del primer testigo'
  report_discrimination_witness_1_email:
    '#title': 'Correo electrónico del primer testigo'
  report_discrimination_add_witness:
    '#title': '¿Agregar otro testigo?'
    '#options':
      'Add another witness': 'Agregar otro testigo'
  report_discrimination_witness_2_name:
    '#title': 'Nombre del segundo testigo'
  report_discrimination_witness_2_phone:
    '#title': 'Teléfono del segundo testigo'
  report_discrimination_witness_2_email:
    '#title': 'Correo electrónico del segundo testigo'
  report_discrimination_file_upload:
    '#title': 'Si corresponde, adjunte fotos u otros materiales relevantes para su queja.'
  report_discrimination_desired_outcome:
    '#title': '¿Qué tipo de acción o resolución le gustaría ver tomada?'
  report_discrimination_filed_complaint_other:
    '#title': '¿Ha presentado una queja ante otras agencias federales, estatales o locales, o dentro de algún tribunal federal o estatal?'
    '#description': 'Tiene derecho a presentar una solicitud ante cualquier agencia o tribunal. Presentar una queja ante otra agencia o tribunal no le impide presentar una queja ante la Ciudad de Portland. En ciertas situaciones, las agencias se coordinarán para asegurarse de que la agencia o el tribunal correspondiente investigue la denuncia.'
    '#options':
      'Yes': Sí
      'No': 'No'
      'Prefer not to answer': 'Prefiero no responder'
  report_discrimination_filed_complaint_other_agency:
    '#title': '¿Qué agencia o tribunal?'
  report_discrimination_filed_complaint_other_agency_contact_name:
    '#title': 'Persona de contacto de la agencia o del tribunal'
  report_discrimination_filed_complaint_other_agency_contact_phone:
    '#title': 'Teléfono de contacto de la agencia o tribunal'
  report_discrimination_on_behalf_of:
    '#title': '¿A nombre de quién realiza esta solicitud o denuncia?'
    '#options':
      Myself: 'Mí mismo'
      'Someone else': 'Alguien más'
  report_discrimination_on_behalf_of_name:
    '#title': '¿Cuál es su nombre?'
  report_discrimination_on_behalf_of_relationship:
    '#title': '¿Cuál es tu relación con ellos?'
  report_discrimination_on_behalf_of_permission:
    '#title': '¿Ha obtenido permiso de ellos para presentar esta denuncia? O, ¿tiene una relación jurídica que le permita presentar una denuncia en su nombre?'
  report_discrimination_on_behalf_of_permission_text_stop:
    '#markup': '<div class="webform-alert alert alert--info"><h2>Próximos pasos</h2><p> Obtenga su permiso antes de enviar este formulario.</p></div>'
  contact_name:
    '#title': 'Su nombre'
  contact_email:
    '#title': 'Correo electrónico'
    '#description': 'Usaremos su correo electrónico para confirmar su envío.'
  contact_phone:
    '#title': Teléfono
  contact_preferred_method:
    '#title': 'Si es necesario, ¿preferiría que nos comuniquemos con usted por teléfono o correo electrónico?'
    '#options':
      Phone: Teléfono
      Email: 'Correo electrónico'
  contact_interpreter:
    '#title': '¿Necesitas un intérprete?'
    '#options':
      'No': 'No'
      'Yes, VRI (Video Remote Interpretation)': 'Sí, VRI (Video Interpretación Remota)'
      'Yes, Oregon Relay Service': 'Sí, servicio de retransmisión de Oregón'
      'Yes, language interpreter': 'Sí, intérprete de idiomas.'
  contact_language:
    '#title': '¿Cual idioma?'
  markup_complainant_acknowledgement_text:
    '#markup': '<p><strong>Acuse de recibo del denunciante</strong></p><p> Al enviar este formulario, afirmo que (1) he leído, entiendo y acepto los <a href="/code/23">términos de los procedimientos para rastrear e investigar quejas de derechos civiles</a> y (2) la información que proporcioné en este formulario es verdadera según mi leal saber y entender.</p>'
  complainant_acknowledgement_agree:
    '#title': 'Estoy de acuerdo'
  section_agent_use_only:
    '#title': 'Solo para uso del agente'
  agent_email:
    '#title': 'Correo electrónico del agente'
    '#default_value': '[usuario-actual:nombre-display] <[usuario-actual:correo]>'
  agent_ticket_number:
    '#title': 'Numero de ticket'
  agent_action_taken:
    '#title': 'Acción tomada'
  agent_contact_type:
    '#title': 'Tipo de Contacto'
  agent_ticket_type:
    '#title': 'Tipo de billete'
  agent_summary:
    '#title': 'Resumen del agente'
  report_ticket_id:
    '#title': 'Informar ID de ticket'
  actions:
    '#title': 'Botones de envío'
    '#submit__label': Enviar
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_new_ticket:
    label: 'Boleto nuevo de Zendesk'
    notes: 'Crea un nuevo ticket de queja por Discriminación y lo asigna al grupo 311: ADA y Discriminación.'
