elements: |
  report_acknowledgement:
    '#title': Reconocimiento
  report_confirm_non_emergency:
    '#title': '¿Se trata de una situación urgente y que pone en peligro la vida, donde alguien está herido o hay un incendio activo?'
  markup_urgent_public:
    '#markup': '<div class="alert alert--warning next-steps"><p><strong>Deje de completar este formulario y llame al 911.</strong></p></div>'
  markup_01:
    '#markup': '<p><strong>Seleccione para continuar.</strong></p>'
  markup:
    '#markup': '<p><em><strong>Durante los períodos de alta demanda del año, las fuerzas del orden no tienen recursos para responder a todas las llamadas que no son de emergencia. Los investigadores de incendios investigarán todos los incendios que tengan conexión con fuegos artificiales y los infractores serán considerados responsables.</strong></em></p>'
  report_location_of_reporter:
    '#location_address__title': 'Comparta su ubicación cuando escuche los fuegos artificiales'
    '#location_address__description': 'Por ejemplo, la dirección de su domicilio'
    '#unit_number__title': 'Número de unidad'
    '#location_city__title': Ciudad
    '#location_state__title': Estado
    '#location_zip__title': 'Código postal'
  report_confirm_known_location:
    '#title': '¿Conoce la ubicación desde donde se están lanzando los fuegos artificiales?'
  report_incident_location:
    '#title': 'Ubicación del incidente'
  report_location:
    '#title': 'Ubicación del incidente'
    '#location_search__title': 'Búsqueda de ubicación'
    '#location_search__description': '<p>Busque en el mapa una dirección, calles transversales, parque o centro comunitario. O use el mapa para seleccionar una ubicación.</p>'
    '#location_details__title': 'Detalles de la ubicación'
    '#location_details__description': 'Dé cualquier otra información que pueda ayudarnos a localizar el sitio que está reportando.'
  report_date:
    '#title': 'Fecha del incidente'
  report_time:
    '#title': 'Hora aproximada del incidente'
  report_incident_description:
    '#title': 'Dé una descripción útil del incidente'
    '#description': '<p>Por ejemplo: color de la casa, propietario, vehículos asociados, o si tiene videos o material multimedia del incidente. Si es necesario, alguien se comunicará con usted con instrucciones sobre cómo enviar fotos o videos.</p>'
  section_contact:
    '#title': 'Su información de contacto'
    '#description': '<p>Tenga en cuenta: Debido a recursos limitados, NO debe esperar una respuesta a este reporte.</p>'
  contact_name:
    '#title': Nombre
  contact_email:
    '#title': 'Correo electrónico'
    '#description': '<p>Usaremos su correo electrónico para confirmar su envío.</p>'
  contact_phone:
    '#title': Teléfono
  section_confidentiality:
    '#title': Confidencialidad
  confidentiality_waiver:
    '#title': 'Exención de confidencialidad'
    '#description': '<p>Es política de la Ciudad mantener confidencial la información que usted da en este formulario con el fin de cumplir con su solicitud. La Ciudad también intentará mantener su información confidencial en caso de que alguien solicite su revelación como registro público conforme a la <a href="https://www.portland.gov/attorney/oregon-public-records-law">Ley de Registros Públicos de Oregón</a>. Si prefiere renunciar a esta confidencialidad, seleccione la opción correspondiente abajo.</p>'
    '#options':
      'I do not waive confidentiality': '<em>No</em> renuncio a la confidencialidad.'
      'I waive confidentiality': 'Elijo renunciar a la confidencialidad.'
  support_agent_use_only:
    '#title__title': ''
