title: 'Reportar un E-Scooter'
description: 'Recopila el informe del miembro de la comunidad, crea un ticket en Zendesk usando la API y envía una notificación a la empresa de scooters. NOTA: Si cambia la dirección de correo electrónico de cualquiera de las compañías de scooters, debe actualizarse en el campo de ramita computada comptued_recipient.'
category: Reporte
elements: |
  section_public_records_statement:
    '#title': 'Declaración de registros públicos'
  public_records_statement_standard:
    '#markup': 'La información que usted proporciona a la Ciudad es un registro público y puede estar sujeta a divulgación conforme a la <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Bajo%20la%20ley%20de%20registros%20públicos%20deOregón,comité%20de%20la%20asamblea%20legislativa%20">Ley de Registros Públicos</a> de Oregón. Esta ley clasifica cierta información como disponible al público previa solicitud. Consulte nuestra <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">declaración de privacidad</a> para obtener más información.'
  section_report:
    '#title': Reporte
  report_issue:
    '#title': '¿Cuál es el problema con el e-scooter?'
    '#options':
      'improperly parked': 'E-scooter está mal estacionado'
      damaged: 'El scooter eléctrico está dañado o no funciona correctamente'
      'riding on sidewalk': 'El usuario está montando en una acera'
    '#other__option_label': 'Algo más...'
    '#other__placeholder': 'Por favor describa...'
    '#admin_notes': '¡IMPORTANTE! Las cadenas de valor para este campo se utilizan en los campos de ramita calculada computed_blocking y computed_private_property. Si se cambian los valores, asegúrese de que la lógica twig se actualice en consecuencia.'
  report_blocking:
    '#title': '¿El e-scooter está bloqueando una acera, un sendero, un carril para bicicletas, un camino de acceso, una calle, una parada de tránsito u otro tipo de carril de transporte?'
  report_private_property:
    '#title': '¿El e-scooter está estacionado en una propiedad privada?'
  report_company:
    '#title': 'Empresa de patinetes eléctricos (e-scooter)'
    '#description': '¿A qué compañía de e-scooter pertenece el scooter? O, ¿de qué color es el e-scooter?'
    '#options':
      Bird: 'Pájaro (negro)'
      Bolt: 'Perno (negro y amarillo)'
      Lime: 'Verde lima)'
      Spin: 'Girar (naranja)'
      'E-scooter company not specified': 'No estoy seguro'
  report_asset_id:
    '#title': 'ID de patinete eléctrico'
  report_location:
    '#title': Ubicación
    '#default_value':
      location_type: calle
      location_park: null
      location_address: null
      place_name: null
      location_details: null
      location_lat: null
      location_lon: null
      location_private_owner: null
    '#location_type__title': '¿En qué tipo de propiedad se encuentra el problema?'
    '#location_park_container__title': 'Contenedor de lista de parques'
    '#waterway_instructions__title': 'Instrucciones de navegación'
    '#location_private_owner__title': '¿Es usted el dueño de la propiedad?'
    '#location_address__title': 'Dirección o cruce de calles'
    '#location_map__title': 'Mapa de localización'
    '#suggestions_modal__title': Sugerencias
    '#status_modal__title': 'Indicador de estado'
    '#place_name__title': 'Ponga su nombre'
    '#location_details__title': 'Detalles de ubicación'
    '#location_lat__title': Latitud
    '#location_lon__title': Longitud
    '#location_asset_id__title': 'ID de activo'
    '#geojson_layer__title': null
    '#geojson_layer_behavior__title': null
  report_photo:
    '#title': Foto
    '#description': 'Si corresponde, incluya hasta 3 fotos del problema que está informando.'
  section_contact:
    '#title': 'tu información de contacto'
  contact_name:
    '#title': 'Su nombre'
  contact_email:
    '#title': 'Tu correo electrónico'
    '#description': 'La ciudad de Portland y la compañía de e-scooter seleccionada usarán su correo electrónico para confirmar su envío y responder si es necesario.'
  section_agent_use_only:
    '#title': 'Solo para uso del agente'
  agent_email:
    '#title': 'Correo electrónico del agente'
    '#default_value': '[usuario-actual:nombre-display] <[usuario-actual:correo]>'
  agent_ticket_number:
    '#title': 'Numero de ticket'
  agent_action_taken:
    '#title': 'Acción tomada'
  agent_contact_type:
    '#title': 'Tipo de Contacto'
  agent_ticket_type:
    '#title': 'Tipo de billete'
    '#default_value': Problema
  company_sla:
    '#title': 'Expectativa de nivel de servicio (en horas)'
  agent_summary:
    '#title': 'Resumen del agente'
  computed_blocking:
    '#title': 'Bloqueo calculado'
  computed_private_property:
    '#title': 'propiedad privada computada'
  computed_urgency:
    '#title': 'Urgencia calculada'
  computed_urgency_text:
    '#title': 'Texto de urgencia calculado'
  computed_resolution_url:
    '#title': 'URL de resolución calculada'
  computed_contact_type:
    '#title': 'Tipo de contacto calculado'
  report_ticket_id:
    '#title': 'ID de ticket de soporte'
  computed_recipient:
    '#title': 'Destinatario calculado'
    '#admin_notes': 'Si este campo computado cambia, debe actualizarse en todos los formularios web que envían notificaciones a las empresas de scooters.'
  actions:
    '#title': 'Botones de envío'
    '#submit__label': Enviar
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: '¡Gracias por tu informe!'
  confirmation_message: 'Su envío ha sido recibido y enviado a la compañía de e-scooter correspondiente para su resolución.'
  confirmation_back_label: null
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_create_ticket:
    label: 'Crear ticket de Zendesk'
    notes: 'Utiliza la API de tickets de Zendesk para crear un nuevo ticket de informe de e-scooter en la zona de pruebas y asignarlo al grupo de respuesta de E-scooter. Envía una notificación a la empresa de e-scooter seleccionada. Cubre todos los tipos de problemas, excepto montar en la acera.'
  zendesk_create_ticket_riding_on_sidewalk:
    label: 'Crear un ticket de Zendesk - Montar en la acera'
    notes: 'Utiliza la API de tickets de Zendesk para crear un nuevo ticket de informe de e-scooter en la zona de pruebas y asignarlo al grupo de respuesta de E-scooter. Esto es solo para la opción Montar en la acera, que se crea como resuelta. Se activa tanto si se selecciona una empresa como si no.'
  email_notification_company:
    label: 'Notificación por correo electrónico a la compañía de scooters'
    notes: null
    settings:
      from_name: null
      reply_to: null
      return_path: null
      sender_name: null
      body: '<p>El siguiente problema de e-scooter se informó a la ciudad de Portland. [webform_submission:valores:computed_urgency_text]</p><p> <strong>¿Cuál es el problema con el e-scooter?</strong> [webform_submission:valores:report_issue]</p><p> <strong>Empresa de scooters eléctricos:</strong> [webform_submission:values:report_company:raw]</p><p> <strong>¿El e-scooter está bloqueando una acera, un sendero, un carril para bicicletas, un camino de entrada, una calle, una parada de tránsito u otro tipo de carril de transporte?</strong> [webform_submission:valores:bloqueo_computado]</p><p> <strong>¿El e-scooter está estacionado en una propiedad privada?</strong> [webform_submission:values:computed_private_property]</p><p> <strong>ID de patinete eléctrico:</strong> [webform_submission:values:report_asset_id]</p><p> <strong>Ubicación:</strong><br /> Dirección: <a href="https://www.google.com/maps/place/[webform_submission:values:report_location:location_address]">[envío_formulario_web:valores:ubicación_informe:dirección_ubicación]</a><br /> Lat/Lon: <a href="https://www.google.com/maps/place/[webform_submission:values:report_location:location_lat],[webform_submission:values:report_location:location_lon]">[envío_formulario web:valores:ubicación_informe:ubicación_lat],[envío_formulario_web:valores:ubicación_informe:ubicación_lon]</a><br /> Nombre del lugar: [envío_formulario_web:valores:ubicación_informe:nombre_lugar]<br /> Detalles adicionales: [webform_submission:valores:report_ubicación:ubicación_detalles]</p><p> <strong>Expectativa de nivel de servicio (horas):</strong> [webform_submission:values:company_sla]</p><p> <strong>ID del ticket de soporte:</strong> [webform_submission:values:report_ticket_id]</p><div style="padding: 10px 20px; background-color: #dddddd;"><p> <strong><a href="[webform_submission:values:computed_resolution_url]">Informar de la resolución de este problema</a></strong></p></div>'
  email_notification_company_no_resolution:
    label: 'Notificación por correo electrónico a la compañía de scooters, no se requiere resolución'
    notes: 'Envía un correo electrónico de notificación a la empresa de e-scooter seleccionada si el problema es Andar en la acera. Solo se envía si se selecciona una empresa.'
    settings:
      from_name: null
      reply_to: null
      return_path: null
      sender_name: null
      body: '<p>El siguiente problema de e-scooter se informó a la ciudad de Portland. [webform_submission:valores:computed_urgency_text]</p><p> <strong>¿Cuál es el problema con el e-scooter?</strong> [webform_submission:valores:report_issue]</p><p> <strong>Empresa de scooters eléctricos:</strong> [webform_submission:values:report_company:raw]</p><p> <strong>¿El e-scooter está bloqueando una acera, un sendero, un carril para bicicletas, un camino de acceso, una calle, una parada de tránsito u otro tipo de carril de transporte?</strong> [webform_submission:valores:bloqueo_computado]</p><p> <strong>¿El e-scooter está estacionado en una propiedad privada?</strong> [webform_submission:values:computed_private_property]</p><p> <strong>ID de patinete eléctrico:</strong> [webform_submission:values:report_asset_id]</p><p> <strong>Ubicación:</strong><br /> Dirección: <a href="https://www.google.com/maps/place/[webform_submission:values:report_location:location_address]">[envío_formulario_web:valores:ubicación_informe:dirección_ubicación]</a><br /> Lat/Lon: <a href="https://www.google.com/maps/place/[webform_submission:values:report_location:location_lat],[webform_submission:values:report_location:location_lon]">[envío_formulario web:valores:ubicación_informe:ubicación_lat],[envío_formulario_web:valores:ubicación_informe:ubicación_lon]</a><br /> Nombre del lugar: [envío_formulario_web:valores:ubicación_informe:nombre_lugar]<br /> Detalles adicionales: [webform_submission:valores:report_ubicación:ubicación_detalles]</p><p> <strong>Expectativa de nivel de servicio (horas):</strong> [webform_submission:values:company_sla]</p><p> <strong>ID del ticket de soporte:</strong> [webform_submission:values:report_ticket_id]</p><div style="padding: 10px 20px; background-color: #dddddd;"><p> Este es un informe Montar en la acera. No es necesaria ninguna resolución.</p></div>'
  email_notification_no_company_selected:
    label: 'Notificación por correo electrónico: ninguna empresa seleccionada'
    notes: 'Cuando el usuario selecciona "No estoy seguro" como la empresa de e-scooter, este controlador envía una notificación a todas las empresas de scooters y les pide que verifiquen sus registros y respondan si su scooter coincide con la ubicación.'
    settings:
      from_name: null
      reply_to: null
      return_path: null
      sender_name: null
      body: '<p>El siguiente problema de e-scooter se informó a la ciudad de Portland. [webform_submission:valores:computed_urgency_text]</p><p style="border: solid 1px red; padding: 5px;"> <strong>NOTA: La empresa de e-scooter no se especificó en este informe. Verifique sus registros para determinar si tiene un e-scooter desplegado en esta ubicación y responda en consecuencia. De lo contrario, puede ignorar este informe.</strong></p><p> <strong>¿Cuál es el problema con el e-scooter?</strong> [webform_submission:valores:report_issue]</p><p> <strong>Empresa de scooters eléctricos:</strong> [webform_submission:values:report_company:raw]</p><p> <strong>¿El e-scooter está bloqueando una acera, un sendero, un carril para bicicletas, un camino de acceso, una calle, una parada de tránsito u otro tipo de carril de transporte?</strong> [webform_submission:valores:bloqueo_computado]</p><p> <strong>¿El e-scooter está estacionado en una propiedad privada?</strong> [webform_submission:values:computed_private_property]</p><p> <strong>ID de patinete eléctrico:</strong> [webform_submission:values:report_asset_id]</p><p> <strong>Ubicación:</strong><br /> Dirección: <a href="https://www.google.com/maps/place/[webform_submission:values:report_location:location_address]">[envío_formulario_web:valores:ubicación_informe:dirección_ubicación]</a><br /> Lat/Lon: <a href="https://www.google.com/maps/place/[webform_submission:values:report_location:location_lat],[webform_submission:values:report_location:location_lon]">[envío_formulario web:valores:ubicación_informe:ubicación_lat],[envío_formulario_web:valores:ubicación_informe:ubicación_lon]</a><br /> Nombre del lugar: [envío_formulario_web:valores:ubicación_informe:nombre_lugar]<br /> Detalles adicionales: [webform_submission:valores:report_ubicación:ubicación_detalles]</p><p> <strong>Expectativa de nivel de servicio (horas):</strong> [webform_submission:values:company_sla]</p><p> <strong>ID del ticket de soporte:</strong> [webform_submission:values:report_ticket_id]</p><div style="padding: 10px 20px; background-color: #dddddd;"><p> <strong><a href="[webform_submission:values:computed_resolution_url]">Informar de la resolución de este problema</a></strong></p></div>'
