settings:
  default_submit_button_label: 送信
  default_reset_button_label: リセット
  default_wizard_prev_button_label: '＜ 前のページ'
  default_wizard_next_button_label: '次のページ ＞'
  default_wizard_start_label: 開始
  default_wizard_confirmation_label: 完了
  default_preview_next_button_label: プレビュー
  default_preview_prev_button_label: '< 前へ'
  default_preview_label: プレビュー
  default_preview_message: 送信内容を確認してください。あなたが送信した内容は「送信」ボタンを押すまで完了しません。
  default_draft_button_label: 下書きを保存
  default_draft_saved_message: 送信は保存されました。後ほどこのフォームに戻ってくると現在の値が保存された状態になっています。
  default_draft_loaded_message: 一部のみが完了したフォームが見つかりました。残りの部分を完成させてください。
  default_previous_submission_message: 'あなたはすでのこのウェブフォームを送信しています。<a href="#">こちらから前回の送信内容をご覧ください。</a>.'
  default_previous_submissions_message: 'あなたはすでのこのウェブフォームを送信しています。<a href="#">こちらから前回の送信内容をご覧ください。</a>.'
  dialog_options:
    narrow:
      title: 幅狭
    normal:
      title: ノーマル
    wide:
      title: ワイド
element:
  default_more_title: 続き
