title: 'Reportar Graffiti - Renuncia'
description: 'Permite que el dueño de una propiedad o su sustituto aprueben una exención de remediación de graffiti para su propiedad y actualiza el ticket de Zendesk asociado'
category: Reporte
elements: |
  waiver_introduction_text:
    '#markup': '<p>Para realizar el trabajo de remediación de graffiti, la Ciudad de Portland necesita su aprobación. Por favor revise y complete este formulario.<br /><br /> Fusce en facilisis urna. Phasellus in tempus nisl, eget vulputate nibh. Sed vestibulum ullamcorper neque at imperdiet. Etiam molestie eget ante eu pharetra. In eget auctor lacus. Morbi vel finibus tellus, quis dictum leo. Proin at rhoncus tortor, in consectetur nisl.</p><p> Praesent suscipit libero turpis. Donec et sollicitudin tortor. Mauris semper semper risus, quis faucibus lectus tristique eget. Nullam in nulla malesuada, bibendum turpis at, sagittis quam.</p>'
  property_type:
    '#title': 'tipo de propiedad'
    '#other__option_label': 'Algo más...'
    '#other__placeholder': 'Por favor describa...'
  property_address:
    '#title': 'Dirección de Propiedad'
  section_contact:
    '#title': 'tu información de contacto'
  contact_name:
    '#title': Nombre
  contact_email:
    '#title': 'Correo electrónico'
  section_waiver:
    '#title': 'Renuncia y Acuerdo'
  waiver_text:
    '#markup': '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nisl magna, placerat non nulla nec, vehicula vestibulum elit. Vivamus sed fringilla massa.</p><ol><li> Mauris en pelentesco sapiens. Nullam quis tellus eget metus vulputate volutpat.</li><li> Proin fermentum commodo metus, a scelerisque leo efficitur et. Phasellus gravida vel tellus vitae dignissim.</li><li> Fusce en facilisis urna. Phasellus in tempus nisl, eget vulputate nibh. Sed vestibulum ullamcorper neque at imperdiet. Etiam molestie eget ante eu pharetra. In eget auctor lacus.</li><li> Morbi vel finibus tellus, quis dictum leo. Proin at rhoncus tortor, in consectetur nisl.</li></ol><p> Praesent suscipit libero turpis. Donec et sollicitudin tortor. Mauris semper semper risus, quis faucibus lectus tristique eget. Nullam in nulla malesuada, bibendum turpis at, sagittis quam.</p>'
  waiver_agreement:
    '#title': 'Estoy de acuerdo'
  public_records_statement_standard:
    '#markup': 'La información que usted proporciona a la Ciudad es un registro público y puede estar sujeta a divulgación conforme a la <a data-renderer-mark="true" href="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~:text=Under%20Oregon''s%20Public%20Records%20Law,committee%20of%20the%20Legislative%20Assembly" title="https://www.doj.state.or.us/oregon-department-of-justice/public-records/attorney-generals-public-records-and-meetings-manual/i-public-records/#:~: text=Bajo%20la%20ley%20de%20registros%20públicos%20deOregón,comité%20de%20la%20asamblea%20legislativa%20">Ley de Registros Públicos</a> de Oregón. Esta ley clasifica cierta información como disponible al público previa solicitud. Consulte nuestra <a data-renderer-mark="true" href="/help/about/privacy" title="https://www.portland.gov/help/about/privacy">declaración de privacidad</a> para obtener más información.'
  report_ticket_id:
    '#title': 'ID de ticket de soporte'
  original_submission_key:
    '#title': 'Clave de envío original'
  actions:
    '#title': 'Botones de envío'
settings:
  form_open_message: null
  form_close_message: null
  form_exception_message: null
  form_confidential_message: null
  form_access_denied_title: null
  form_access_denied_message: null
  submission_label: null
  submission_exception_message: null
  submission_locked_message: null
  submission_access_denied_title: null
  submission_access_denied_message: null
  previous_submission_message: null
  previous_submissions_message: null
  autofill_message: null
  wizard_start_label: null
  wizard_confirmation_label: null
  wizard_prev_button_label: null
  wizard_next_button_label: null
  wizard_toggle_show_label: null
  wizard_toggle_hide_label: null
  preview_label: null
  preview_title: null
  preview_message: null
  draft_saved_message: null
  draft_loaded_message: null
  draft_pending_single_message: null
  draft_pending_multiple_message: null
  confirmation_url: null
  confirmation_title: null
  confirmation_message: null
  confirmation_back_label: 'Enviar otro informe'
  limit_total_message: null
  limit_user_message: null
handlers:
  zendesk_ticket_validator:
    label: 'Validador de tickets de Zendesk'
    notes: null
  zendesk_update_ticket:
    label: 'Ticket de actualización de Zendesk'
    notes: null
